const styles = {
  pageContainer: { fontFamily: "'Poppins', sans-serif" },
  pageHeader: { marginBottom: "24px" },
  headerTitle: { fontSize: "2.25rem", fontWeight: 700, color: "#1a202c" },
  controlsHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "24px",
    gap: "16px",
  },
  searchBox: {
    flexGrow: 1,
    display: "flex",
    alignItems: "center",
    background: "#fff",
    borderRadius: "12px",
    padding: "0 16px",
    border: "1px solid #e5e7eb",
    boxShadow: "0px 4px 20px rgba(0, 0, 0, 0.04)",
  },
  searchIcon: { color: "#9ca3af" },
  searchInput: {
    flexGrow: 1,
    border: "none",
    outline: "none",
    padding: "12px 8px",
    background: "transparent",
    fontFamily: "'Poppins', sans-serif",
    fontSize: "0.9rem",
  },
  createButton: {
    backgroundColor: "#3b82f6",
    color: "#fff",
    border: "none",
    borderRadius: "12px",
    padding: "12px 20px",
    fontWeight: 500,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    transition: "all 0.2s",
  },
  tableCard: {
    background: "rgba(255, 255, 255, 0.6)",
    backdropFilter: "blur(10px)",
    WebkitBackdropFilter: "blur(10px)",
    borderRadius: "16px",
    border: "1px solid rgba(255, 255, 255, 0.25)",
    boxShadow: "0px 4px 20px rgba(0, 0, 0, 0.04)",
    padding: "16px",
    overflowX: "auto",
  },
  table: { width: "100%", borderCollapse: "collapse" },
  tableHeader: {
    padding: "16px 20px",
    textAlign: "left",
    borderBottom: "1px solid #f3f4f6",
    fontSize: "0.75rem",
    color: "#6b7280",
    textTransform: "uppercase",
    fontWeight: 600,
  },
  tableRow: { cursor: "pointer", transition: "background-color 0.2s" },
  tableRowHover: { backgroundColor: "rgba(249, 250, 251, 0.7)" },
  tableCell: {
    padding: "16px 20px",
    textAlign: "left",
    borderBottom: "1px solid #f3f4f6",
    fontSize: "0.9rem",
    color: "#2d3748",
    fontWeight: 500,
  },
  statusBadge: {
    padding: "4px 10px",
    borderRadius: "12px",
    fontSize: "0.75rem",
    fontWeight: 600,
  },
  statusAtivo: { backgroundColor: "#def7ec", color: "#03543f" },
  statusInativo: { backgroundColor: "#fee2e2", color: "#991b1b" },
  paginationContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "24px 0 8px 0",
    gap: "16px",
  },
  paginationSpan: { fontSize: "0.9rem", color: "#6b7280" },
  paginationButton: {
    backgroundColor: "#fff",
    border: "1px solid #e5e7eb",
    color: "#374151",
    padding: "8px 16px",
    borderRadius: "8px",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  paginationButtonDisabled: { opacity: 0.5, cursor: "not-allowed" },
};
export default styles;
