const styles = {
  pageContainer: { fontFamily: "'Poppins', sans-serif" },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "32px",
    marginTop: "40px",
    paddingBottom: "24px",
    borderBottom: "1px solid #e2e8f0",
  },
  headerLeft: { display: "flex", alignItems: "center", gap: "16px" },
  backButton: {
    background: "#fff",
    border: "1px solid #e2e8f0",
    width: "40px",
    height: "40px",
    borderRadius: "12px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "1rem",
    color: "#4b5563",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  headerTitle: {
    margin: 0,
    fontSize: "2rem",
    fontWeight: 700,
    color: "#1e293b",
  },
  headerActions: { display: "flex", gap: "12px" },
    actionButton: {
    background: '#fff',
    border: '1px solid #d1d5db',
    color: '#374151',
    borderRadius: '12px',
    padding: '10px 16px',
    fontWeight: 500,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    transition: 'all 0.2s',
  },
  editButton: {
    backgroundColor: "#3b82f6",
    color: "#fff",
    border: "none",
    borderRadius: "12px",
    padding: "10px 18px",
    fontWeight: 600,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  saveButton: {
    backgroundColor: "#10b981",
    color: "#fff",
    border: "none",
    borderRadius: "12px",
    padding: "10px 18px",
    fontWeight: 600,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  cancelButton: {
    background: "#e5e7eb",
    color: "#374151",
    border: "none",
    borderRadius: "12px",
    padding: "10px 18px",
    fontWeight: 600,
  },

  mainGrid: {
    display: "grid",
    gridTemplateColumns: "2fr 1fr",
    gap: "32px",
    alignItems: "flex-start",
  },
  leftColumn: { display: "flex", flexDirection: "column", gap: "24px" },
  rightColumn: {
    position: "sticky",
    top: "20px",
    display: "flex",
    flexDirection: "column",
    gap: "24px",
  },

  infoCard: {
    background: "rgba(255, 255, 255, 0.7)",
    backdropFilter: "blur(10px)",
    borderRadius: "16px",
    padding: "24px",
    border: "1px solid #e2e8f0",
  },
  cardTitle: {
    fontSize: "1.125rem",
    fontWeight: 600,
    color: "#1e293b",
    margin: "0 0 16px 0",
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  infoGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: "16px",
  },
  infoGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "4px"
  },
  infoLabel: {
    display: "block",
    fontSize: "0.8rem",
    color: "#6b7280",
    textTransform: "uppercase",
    fontWeight: 500,
  },
  infoValue: {
    fontSize: "0.95rem",
    color: "#2d3748",
    fontWeight: 500,
    margin: 0,
    background: "#fff",
    padding: "10px 12px",
    borderRadius: "8px",
    border: "1px solid #e5e7eb",
    minHeight: "42px",
    display: "flex",
    alignItems: "center",
  },
  formInput: {
    width: "100%",
    boxSizing: "border-box",
    fontSize: "0.95rem",
    color: "#2d3748",
    fontWeight: 500,
    margin: 0,
    background: "#fff",
    padding: "10px 12px",
    borderRadius: "8px",
    border: "1px solid #e5e7eb",
  },
  formSelect: {
    width: "100%",
    boxSizing: "border-box",
    fontSize: "0.95rem",
    color: "#2d3748",
    fontWeight: 500,
    margin: 0,
    background: "#fff",
    padding: "10px 12px",
    borderRadius: "8px",
    border: "1px solid #e5e7eb",
  },
};
export default styles;