const styles = {
  modalBackdrop: {
    position: "fixed",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    backgroundColor: "rgba(0, 0, 0, 0.3)",
    backdropFilter: "blur(8px)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  modalContent: {
    background: "rgba(249, 250, 251, 0.9)",
    borderRadius: "20px",
    padding: "28px",
    width: "90%",
    maxWidth: "500px",
  },
  modalHeader: { marginBottom: "16px" },
  modalTitle: {
    fontSize: "1.5rem",
    fontWeight: 600,
    color: "#1f2937",
    margin: 0,
  },
  searchBox: { position: "relative", width: "100%", marginBottom: "12px" },
  searchInput: {
    width: "100%",
    boxSizing: "border-box",
    fontFamily: "'Poppins', sans-serif",
    fontSize: "1rem",
    padding: "12px 16px 12px 40px",
    border: "1px solid #d1d5db",
    borderRadius: "12px",
    backgroundColor: "#fff",
  },
  searchIcon: {
    position: "absolute",
    left: "16px",
    top: "50%",
    transform: "translateY(-50%)",
    color: "#9ca3af",
  },
  resultsList: {
    listStyle: "none",
    padding: 0,
    margin: "0",
    maxHeight: "250px",
    overflowY: "auto",
  },
  resultItem: {
    padding: "12px 16px",
    cursor: "pointer",
    borderBottom: "1px solid #f3f4f6",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  resultItemHover: { backgroundColor: "#f3f4f6" },
  noResults: { padding: "12px 16px", color: "#9ca3af", textAlign: "center" },
  modalFooter: {
    display: "flex",
    justifyContent: "flex-end",
    marginTop: "24px",
  },
  closeButton: {
    background: "#e5e7eb",
    color: "#374151",
    border: "none",
    borderRadius: "10px",
    padding: "10px 20px",
    fontWeight: 600,
    cursor: "pointer",
  },
};
export default styles;
