const styles = {
    // Estilos da Página
    withdrawalsPageContainer: { fontFamily: "'Poppins', sans-serif" },
    withdrawalsPageHeader: { marginBottom: '24px' },
    headerH1: { fontSize: '2.25rem', fontWeight: 700, color: '#1a202c' },
    withdrawalKpiCards: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '24px', marginBottom: '32px' },
    withdrawalKpiCard: { background: 'rgba(255, 255, 255, 0.6)', backdropFilter: 'blur(10px)', WebkitBackdropFilter: 'blur(10px)', borderRadius: '16px', border: '1px solid rgba(255, 255, 255, 0.25)', boxShadow: '0px 4px 20px rgba(0, 0, 0, 0.04)', padding: '24px', display: 'flex', alignItems: 'center', gap: '20px' },
    kpiIcon: { fontSize: '1.5rem', color: '#3b82f6', backgroundColor: 'rgba(59, 130, 246, 0.1)', width: '48px', height: '48px', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
    kpiH4: { margin: '0 0 4px 0', fontSize: '0.9rem', fontWeight: 500, color: '#4a5568' },
    kpiMainValue: { fontSize: '1.75rem', fontWeight: 700, color: '#1a202c', margin: 0 },
    kpiUnit: { fontSize: '1rem', color: '#9ca3af' },
    kpiSubValue: { fontSize: '0.85rem', color: '#718096', margin: '2px 0 0 0' },
    tableControlsHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px' },
    actionsGroup: { display: 'flex', gap: '16px', alignItems: 'center' },
    searchBox: { display: 'flex', alignItems: 'center', background: '#fff', borderRadius: '12px', padding: '0 16px', border: '1px solid #e5e7eb', boxShadow: '0px 4px 20px rgba(0, 0, 0, 0.04)' },
    searchIcon: { color: '#9ca3af' },
    searchInput: { border: 'none', outline: 'none', padding: '12px 8px', background: 'transparent', width: '250px', fontFamily: "'Poppins', sans-serif", fontSize: '0.9rem' },
    createWithdrawalButton: { backgroundColor: '#10b981', color: '#fff', border: 'none', borderRadius: '12px', padding: '12px 20px', fontWeight: 500, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '8px', transition: 'all 0.2s' },
    createWithdrawalButtonHover: { backgroundColor: '#059669', transform: 'translateY(-2px)' },
    
    // Tabela
    withdrawalsTableCard: { background: 'rgba(255, 255, 255, 0.6)', backdropFilter: 'blur(10px)', WebkitBackdropFilter: 'blur(10px)', borderRadius: '16px', border: '1px solid rgba(255, 255, 255, 0.25)', boxShadow: '0px 4px 20px rgba(0, 0, 0, 0.04)', padding: '16px', overflowX: 'auto' },
    withdrawalsTable: { width: '100%', borderCollapse: 'collapse' },
    tableHeaderCell: { padding: '16px 20px', textAlign: 'left', borderBottom: '1px solid #f3f4f6', fontSize: '0.75rem', color: '#6b7280', textTransform: 'uppercase', fontWeight: 600 },
    tableCell: { padding: '16px 20px', textAlign: 'left', borderBottom: '1px solid #f3f4f6', fontSize: '0.9rem', color: '#2d3748', fontWeight: 500 },
    viewAccountBtn: { background: 'none', border: '1px solid #d1d5db', color: '#374151', padding: '6px 12px', borderRadius: '8px', cursor: 'pointer', transition: 'all 0.2s' },
    viewAccountBtnHover: { backgroundColor: '#f3f4f6', borderColor: '#9ca3af' },
    statusBadge: { padding: '4px 10px', borderRadius: '12px', fontSize: '0.75rem', fontWeight: 600 },
    statusPendente: { backgroundColor: '#fef3c7', color: '#92400e' },
    statusAprovado: { backgroundColor: '#def7ec', color: '#03543f' },
    statusNegado: { backgroundColor: '#fee2e2', color: '#991b1b' },
    actionButtons: { display: 'flex', gap: '8px' },
    actionButton: { border: 'none', width: '32px', height: '32px', borderRadius: '8px', cursor: 'pointer', fontSize: '0.9rem', color: '#fff', transition: 'all 0.2s', display: 'flex', alignItems: 'center', justifyContent: 'center' },
    approveBtn: { backgroundColor: '#10b981' },
    approveBtnHover: { backgroundColor: '#059669' },
    denyBtn: { backgroundColor: '#ef4444' },
    denyBtnHover: { backgroundColor: '#dc2626' },
    
    // Paginação
    paginationContainer: { display: 'flex', justifyContent: 'center', alignItems: 'center', padding: '24px 0 8px 0', gap: '16px' },
    paginationSpan: { fontSize: '0.9rem', color: '#6b7280' },
    paginationButton: { backgroundColor: '#fff', border: '1px solid #e5e7eb', color: '#374151', padding: '8px 16px', borderRadius: '8px', cursor: 'pointer', transition: 'all 0.2s' },
    paginationButtonHover: { backgroundColor: '#f3f4f6', borderColor: '#d1d5db' },
    paginationButtonDisabled: { opacity: 0.5, cursor: 'not-allowed' },

    // Dropdown
    customDropdownContainer: { position: 'relative' },
    dropdownHeader: { background: '#fff', border: '1px solid #e5e7eb', borderRadius: '12px', padding: '12px 16px', fontFamily: "'Poppins', sans-serif", fontSize: '0.9rem', cursor: 'pointer', display: 'flex', justifyContent: 'space-between', alignItems: 'center', width: '180px', textAlign: 'left' },
    dropdownHeaderIcon: { transition: 'transform 0.2s ease', color: '#9ca3af' },
    dropdownHeaderIconOpen: { transform: 'rotate(180deg)' },
    dropdownList: { position: 'absolute', top: '110%', right: 0, width: '100%', background: '#fff', borderRadius: '8px', border: '1px solid #e5e7eb', boxShadow: '0 10px 20px rgba(0,0,0,0.07)', listStyle: 'none', padding: '8px', margin: 0, zIndex: 10 },
    dropdownListItem: { padding: '8px 12px', borderRadius: '6px', cursor: 'pointer' },
    dropdownListItemHover: { backgroundColor: '#f3f4f6' },

    // Modais
    modalBackdrop: { position: 'fixed', top: 0, left: 0, width: '100%', height: '100%', backgroundColor: 'rgba(0, 0, 0, 0.2)', backdropFilter: 'blur(8px)', WebkitBackdropFilter: 'blur(8px)', display: 'flex', justifyContent: 'center', alignItems: 'center', zIndex: 1000 },
    modalContent: { background: 'rgba(249, 250, 251, 0.9)', borderRadius: '20px', border: '1px solid rgba(255, 255, 255, 0.3)', boxShadow: '0 10px 30px rgba(0,0,0,0.1)', padding: '28px', position: 'relative' },
    modalContentSmall: { width: '90%', maxWidth: '500px' },
    modalContentLarge: { width: '90%', maxWidth: '700px' },
    modalHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px' },
    modalHeaderH3: { fontSize: '1.5rem', color: '#1a202c', margin: 0 },
    modalHeaderButton: { background: 'none', border: 'none', fontSize: '1.2rem', cursor: 'pointer', color: '#9ca3af' },
    bankDetailsP: { margin: '8px 0', fontSize: '1rem', color: '#4a5568' },
    bankDetailsSpan: { fontWeight: 600, color: '#2d3748' },
    wizardSteps: { display: 'flex', justifyContent: 'space-around', marginBottom: '24px', borderBottom: '1px solid #e5e7eb', paddingBottom: '16px' },
    wizardStepsSimplified: { justifyContent: 'center', gap: '48px' },
    step: { display: 'flex', alignItems: 'center', gap: '8px', color: '#9ca3af' },
    stepSpan: { width: '24px', height: '24px', borderRadius: '50%', border: '2px solid #d1d5db', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 600 },
    stepActive: { color: '#3b82f6' },
    stepSpanActive: { borderColor: '#3b82f6', backgroundColor: '#3b82f6', color: '#fff' },
    wizardContent: { minHeight: '280px' },
    clientSearchStepInput: { width: '100%', boxSizing: 'border-box', padding: '12px', borderRadius: '8px', border: '1px solid #d1d5db', marginBottom: '12px' },
    clientSearchResults: { listStyle: 'none', padding: 0, margin: 0 },
    clientSearchResultsLi: { padding: '12px', borderRadius: '8px', cursor: 'pointer' },
    clientSearchResultsLiHover: { backgroundColor: '#f3f4f6' },
    contractSelectStepH4: { margin: '0 0 12px 0' },
    contractSelectList: { listStyle: 'none', padding: 0, margin: 0 },
    contractSelectListLi: { padding: '12px', borderRadius: '8px', cursor: 'pointer', display: 'flex', justifyContent: 'space-between' },
    valueStepH4: { textAlign: 'center', fontWeight: 500, color: '#4a5568' },
    availableValue: { color: '#10b981', fontWeight: 700 },
    formGroup: { display: 'flex', flexDirection: 'column', marginTop: '16px', position: 'relative' },
    formGroupLabel: { fontSize: '0.9rem', marginBottom: '8px', textAlign: 'center' },
    formGroupInput: { padding: '12px', borderRadius: '8px', border: '1px solid #d1d5db', fontSize: '1.2rem', textAlign: 'center', transition: 'border-color 0.2s' },
    modalFooter: { display: 'flex', justifyContent: 'space-between', gap: '12px', marginTop: '24px' },
    backBtn: { background: '#e5e7eb', color: '#374151', border: 'none', borderRadius: '12px', padding: '10px 18px', fontWeight: 500 },
    confirmBtn: { backgroundColor: '#10b981', color: '#fff', border: 'none', borderRadius: '12px', padding: '10px 18px', fontWeight: 500, marginLeft: 'auto' },
    paginationContainerModal: { display: 'flex', justifyContent: 'center', alignItems: 'center', paddingTop: '12px', gap: '12px' },
    paginationModalSpan: { fontSize: '0.85rem', color: '#6b7280' },
    paginationModalButton: { backgroundColor: '#f3f4f6', border: '1px solid #e5e7eb', color: '#374151', width: '28px', height: '28px', borderRadius: '50%', cursor: 'pointer', transition: 'all 0.2s' },
    formGroupErrorInput: { borderColor: '#ef4444' },
    errorMessage: { color: '#ef4444', fontSize: '0.8rem', fontWeight: 500, textAlign: 'center', marginTop: '8px' },
    
    // Animação de Sucesso
    successAnimationContainer: { display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: '40px 20px', textAlign: 'center', minHeight: '280px' },
    successCheckmark: { width: '80px', height: '80px' },
};

export default styles;