const styles = {
    createPageContainer: {
      fontFamily: "'Poppins', sans-serif",
      maxWidth: "800px",
      margin: "40px auto 0px auto",
    },
    header: {
      display: "flex",
      alignItems: "center",
      gap: "16px",
      marginBottom: "32px",
    },
    backButton: {
      background: "#fff",
      border: "1px solid #e2e8f0",
      width: "40px",
      height: "40px",
      borderRadius: "12px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: "1rem",
      color: "#4b5563",
      cursor: "pointer",
    },
    headerTitle: {
      fontSize: "2rem",
      fontWeight: 700,
      color: "#1e293b",
      margin: 0,
    },
    wizardCard: {
      background: "rgba(255, 255, 255, 0.7)",
      backdropFilter: "blur(10px)",
      borderRadius: "20px",
      border: "1px solid #e2e8f0",
      padding: "28px",
    },
    wizardSteps: {
      display: "flex",
      justifyContent: "space-between",
      marginBottom: "28px",
      paddingBottom: "20px",
      borderBottom: "1px solid #e5e7eb",
      position: "relative",
    },
    step: {
      display: "flex",
      alignItems: "center",
      gap: "8px",
      color: "#9ca3af",
      fontWeight: 500,
    },
    stepNumber: {
      width: "32px",
      height: "32px",
      borderRadius: "50%",
      border: "2px solid #d1d5db",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontWeight: 600,
      transition: "all 0.3s ease",
    },
    stepActive: { color: "#3b82f6" },
    stepNumberActive: {
      borderColor: "#3b82f6",
      backgroundColor: "#3b82f6",
      color: "#fff",
    },
    wizardContent: {
      minHeight: "300px",
      display: "flex",
      flexDirection: "column",
      justifyContent: "center",
    },
    wizardFooter: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      marginTop: "28px",
      paddingTop: "20px",
      borderTop: "1px solid #e5e7eb",
    },
    footerButton: {
      border: "none",
      borderRadius: "10px",
      padding: "10px 20px",
      fontWeight: 600,
      cursor: "pointer",
      transition: "all 0.2s ease",
    },
    backButtonFooter: {
      background: "#e5e7eb",
      color: "#374151",
    },
    nextButtonFooter: {
      background: "#3b82f6",
      color: "#fff",
    },
    disabledButton: {
      background: "#d1d5db",
      color: "#6b7280",
      cursor: "not-allowed",
    },
    formGroup: {
      display: "flex",
      flexDirection: "column",
      gap: "8px",
      marginBottom: "20px",
    },
    formLabel: {
      fontWeight: 500,
      color: "#374151",
    },
    formInput: {
      padding: "12px 14px",
      borderRadius: "10px",
      border: "1px solid #d1d5db",
      fontSize: "1rem",
    },
    searchResults: {
      maxHeight: "200px",
      overflowY: "auto",
      marginTop: "8px",
    },
    searchResultItem: {
      padding: "12px",
      borderRadius: "8px",
      cursor: "pointer",
    },
    searchMessage: {
      textAlign: 'center',
      color: '#6b7280',
      padding: '20px',
    },
    confirmationList: {
      listStyle: "none",
      padding: 0,
      margin: "0 auto",
      maxWidth: "400px",
    },
    confirmationItem: {
      display: "flex",
      justifyContent: "space-between",
      padding: "12px 0",
      borderBottom: "1px solid #e5e7eb",
    },
    confirmationLabel: { color: "#6b7280" },
    confirmationValue: { fontWeight: 600, color: "#1f2937" },
    successContainer: {
      textAlign: "center",
    },
  };
  
  export default styles;