const styles = {
  withdrawalsPageContainer: { fontFamily: "'Poppins', sans-serif" },
  withdrawalsPageHeader: { marginBottom: "24px" },
  headerH1: { fontSize: "2.25rem", fontWeight: 700, color: "#1a202c" },
  tableControlsHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "24px",
    gap: "16px",
  },
  actionsGroup: { display: "flex", gap: "16px", alignItems: "center" },
  searchBox: {
    flexGrow: 1,
    display: "flex",
    alignItems: "center",
    background: "#fff",
    borderRadius: "12px",
    padding: "0 16px",
    border: "1px solid #e5e7eb",
    boxShadow: "0px 4px 20px rgba(0, 0, 0, 0.04)",
  },
  searchIcon: { color: "#9ca3af" },
  searchInput: {
    border: "none",
    outline: "none",
    padding: "12px 8px",
    background: "transparent",
    fontFamily: "'Poppins', sans-serif",
    fontSize: "0.9rem",
  },
  filterSelect: {
    background: "#fff",
    border: "1px solid #e5e7eb",
    borderRadius: "12px",
    padding: "12px 16px",
    fontFamily: "'Poppins', sans-serif",
    fontSize: "0.9rem",
    cursor: "pointer",
    boxShadow: "0px 4px 20px rgba(0, 0, 0, 0.04)",
    minWidth: "180px",
  },
  createWithdrawalButton: {
    backgroundColor: "#10b981",
    color: "#fff",
    border: "none",
    borderRadius: "12px",
    padding: "12px 20px",
    fontWeight: 500,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    transition: "all 0.2s",
  },
  withdrawalsTableCard: {
    background: "rgba(255, 255, 255, 0.6)",
    backdropFilter: "blur(10px)",
    WebkitBackdropFilter: "blur(10px)",
    borderRadius: "16px",
    border: "1px solid rgba(255, 255, 255, 0.25)",
    boxShadow: "0px 4px 20px rgba(0, 0, 0, 0.04)",
    padding: "16px",
    overflowX: "auto",
  },
  withdrawalsTable: { width: "100%", borderCollapse: "collapse" },
  tableHeaderCell: {
    padding: "16px 20px",
    textAlign: "left",
    borderBottom: "1px solid #f3f4f6",
    fontSize: "0.75rem",
    color: "#6b7280",
    textTransform: "uppercase",
    fontWeight: 600,
  },
  tableRow: { cursor: "pointer", transition: "background-color 0.2s" },
  tableCell: {
    padding: "16px 20px",
    textAlign: "left",
    borderBottom: "1px solid #f3f4f6",
    fontSize: "0.9rem",
    color: "#2d3748",
    fontWeight: 500,
  },
  statusBadge: {
    padding: "4px 10px",
    borderRadius: "12px",
    fontSize: "0.75rem",
    fontWeight: 600,
  },
  statusPendente: { backgroundColor: "#fef3c7", color: "#92400e" },
  statusAprovado: { backgroundColor: "#def7ec", color: "#03543f" },
  statusNegado: { backgroundColor: "#fee2e2", color: "#991b1b" },
  actionButtons: { display: "flex", gap: "8px" },
  actionButton: {
    border: "none",
    width: "32px",
    height: "32px",
    borderRadius: "8px",
    cursor: "pointer",
    fontSize: "0.9rem",
    color: "#fff",
    transition: "all 0.2s",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  approveBtn: { backgroundColor: "#10b981" },
  denyBtn: { backgroundColor: "#ef4444" },
  paginationContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "24px 0 8px 0",
    gap: "16px",
  },
  paginationSpan: { fontSize: "0.9rem", color: "#6b7280" },
  paginationButton: {
    backgroundColor: "#fff",
    border: "1px solid #e5e7eb",
    color: "#374151",
    padding: "8px 16px",
    borderRadius: "8px",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  paginationButtonDisabled: { opacity: 0.5, cursor: "not-allowed" },
  tableRowSelected: {
    backgroundColor: "rgba(59, 130, 246, 0.1)",
  },
  bulkActionsBar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "12px 20px",
    backgroundColor: "#1f2937",
    color: "#fff",
    borderRadius: "12px",
    marginBottom: "24px",
    animation: "fadeIn 0.3s ease",
  },
  bulkActionButton: {
    border: "none",
    borderRadius: "8px",
    padding: "8px 16px",
    marginLeft: "12px",
    fontWeight: 500,
    color: "#fff",
    cursor: "pointer",
  },
};

export default styles;