const styles = {
  pageContainer: {
    fontFamily: "'Poppins', sans-serif",
    width: "100%",
    padding: "24px 32px",
    backgroundColor: "#f8f9fa",
    boxSizing: "border-box",
  },
  loadingContainer: {
    fontFamily: "'Poppins', sans-serif",
    fontSize: "1.2rem",
    color: "#6b7280",
    textAlign: "center",
    padding: "40px",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "32px",
  },
  headerInfo: {
    display: "flex",
    alignItems: "center",
    gap: "20px",
  },
  backButton: {
    background: "#fff",
    border: "1px solid #e5e7eb",
    width: "40px",
    height: "40px",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    color: "#4b5563",
    fontSize: "1rem",
    transition: "all 0.2s",
  },
  avatarContainer: {
    position: "relative",
  },
  avatar: {
    width: "64px",
    height: "64px",
    borderRadius: "50%",
    backgroundColor: "#3b82f6",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "2rem",
    fontWeight: "bold",
    overflow: "hidden",
  },
  avatarImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  removePhotoButton: {
    position: "absolute",
    bottom: "-5px",
    right: "-5px",
    background: "#ef4444",
    color: "white",
    border: "2px solid white",
    borderRadius: "50%",
    width: "28px",
    height: "28px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    fontSize: "0.8rem",
    boxShadow: "0 2px 4px rgba(0,0,0,0.2)",
  },
  clientName: {
    fontSize: "2rem",
    fontWeight: 700,
    color: "#1a202c",
    margin: 0,
  },
  clientEmail: {
    fontSize: "1rem",
    color: "#6b7280",
    margin: "4px 0 0 0",
  },
  headerActions: {
    display: "flex",
    gap: "12px",
  },
  actionButton: {
    background: "#fff",
    border: "1px solid #d1d5db",
    color: "#374151",
    borderRadius: "12px",
    padding: "10px 16px",
    fontWeight: 500,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    transition: "all 0.2s",
  },
  loginButton: {
    backgroundColor: "#f59e0b",
    color: "#fff",
    border: "none",
  },
  statsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, 1fr)",
    gap: "24px",
    marginBottom: "32px",
  },
  statCard: {
    background: "#ffffff",
    borderRadius: "16px",
    border: "1px solid #e5e7eb",
    padding: "20px",
    display: "flex",
    alignItems: "center",
    gap: "16px",
  },
  statIcon: {
    fontSize: "1.25rem",
    color: "#3b82f6",
    backgroundColor: "rgba(59, 130, 246, 0.1)",
    width: "48px",
    height: "48px",
    borderRadius: "12px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  statLabel: {
    margin: "0 0 4px 0",
    fontSize: "0.9rem",
    fontWeight: 500,
    color: "#6b7280",
  },
  statValue: {
    fontSize: "1.5rem",
    fontWeight: 700,
    color: "#111827",
    margin: 0,
  },
  contentGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "24px",
  },
  card: {
    background: "#ffffff",
    borderRadius: "16px",
    border: "1px solid #e5e7eb",
    padding: "24px",
    transition: "all 0.3s ease-in-out",
  },
  cardEditing: {
    borderColor: "#93c5fd",
    boxShadow: "0 0 0 3px rgba(59, 130, 246, 0.2)",
  },
  cardTitleContainer: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    margin: "0 0 20px 0",
    paddingBottom: "16px",
    borderBottom: "1px solid #f3f4f6",
  },
  cardTitle: {
    fontSize: "1.1rem",
    fontWeight: 600,
    color: "#1f2937",
    margin: 0,
  },
  editButton: {
    background: "transparent",
    border: "none",
    color: "#3b82f6",
    borderRadius: "8px",
    padding: "6px 12px",
    fontWeight: 500,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "6px",
    transition: "all 0.2s",
  },
  infoGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "24px",
  },
  infoLabel: {
    fontSize: "0.8rem",
    color: "#6b7280",
    marginBottom: "4px",
    textTransform: "uppercase",
    fontWeight: 500,
    display: "block",
  },
  infoValue: {
    fontSize: "0.95rem",
    color: "#1f2937",
    fontWeight: 500,
    margin: 0,
  },
  inputField: {
    width: "100%",
    padding: "8px 12px",
    fontSize: "0.95rem",
    color: "#1f2937",
    backgroundColor: "#f9fafb",
    border: "1px solid #d1d5db",
    borderRadius: "8px",
    boxSizing: "border-box",
    transition: "border-color 0.2s, box-shadow 0.2s",
  },
  editActions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "12px",
    marginTop: "24px",
    paddingTop: "20px",
    borderTop: "1px solid #f3f4f6",
  },
  saveButton: {
    backgroundColor: "#2563eb",
    color: "white",
    border: "none",
    borderRadius: "12px",
    padding: "10px 16px",
    fontWeight: 500,
    cursor: "pointer",
    transition: "background-color 0.2s",
  },
  cancelButton: {
    background: "#fff",
    border: "1px solid #d1d5db",
    color: "#374151",
    borderRadius: "12px",
    padding: "10px 16px",
    fontWeight: 500,
    cursor: "pointer",
    transition: "background-color 0.2s",
  },
  contractsListContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  // Estilo para o <button> que envolve o contrato, para resetar e parecer um div
  contractItemButton: {
    background: "transparent",
    border: "none",
    padding: "0",
    margin: "0",
    width: "100%",
    textAlign: "left",
    cursor: "pointer",
    borderRadius: "12px", // Para que o foco se ajuste ao item
  },
  contractItem: {
    border: "1px solid #e5e7eb",
    borderRadius: "12px",
    padding: "16px",
    backgroundColor: "#f9fafb",
    transition: "all 0.2s ease-in-out",
  },
  contractHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "16px",
  },
  contractId: {
    fontWeight: 600,
    color: "#1f2937",
  },
  contractStatus: {
    fontSize: "0.8rem",
    fontWeight: 500,
    padding: "4px 10px",
    borderRadius: "9999px",
    textTransform: "capitalize",
  },
  statusActive: { backgroundColor: "#dcfce7", color: "#16a34a" },
  statusFinished: { backgroundColor: "#e0e7ff", color: "#4f46e5" },
  statusCancelled: { backgroundColor: "#fee2e2", color: "#dc2626" },
  statusDefault: { backgroundColor: "#f3f4f6", color: "#4b5563" },
  contractBody: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))",
    gap: "16px",
  },
  contractInfo: { display: "flex", flexDirection: "column" },
  contractInfoLabel: {
    fontSize: "0.8rem",
    color: "#6b7280",
    marginBottom: "2px",
  },
  contractInfoValue: { fontSize: "0.95rem", color: "#111827", fontWeight: 500 },
  loadingText: { color: "#6b7280", textAlign: "center", padding: "20px" },

  // --- ESTILOS PARA PAGINAÇÃO ---
  paginationControls: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  pageInfo: {
    fontSize: "0.9rem",
    color: "#6b7280",
    fontWeight: 500,
  },
  paginationButton: {
    background: "#fff",
    border: "1px solid #d1d5db",
    color: "#4b5563",
    width: "32px",
    height: "32px",
    borderRadius: "8px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    transition: "all 0.2s",
  },
};
// Adicionando pseudo-seletores de forma que o React entenda
styles.paginationButton[":disabled"] = {
  opacity: 0.5,
  cursor: "not-allowed",
};
styles.contractItemButton[":hover"] = {
  // Para aplicar no hover do botão, precisamos de uma solução mais complexa
  // ou simplesmente estilizar o div interno no hover do botão
};
styles.contractItem[":hover"] = {
  // Isso não funciona diretamente. O ideal é usar o do botão.
  // O cursor: pointer no contractItemButton já dá a dica visual.
  // Um leve transform ou boxShadow pode ser adicionado
};

export default styles;
