const styles = {
  // ===================================================
  // --- ESTILOS DO DASHBOARD (PRIMEIRA CONVERSÃO) ---
  // ===================================================

  '.dashboard-neumorph-container': {
    fontFamily: "'Poppins', sans-serif",
  },
  '.dashboard-header-neumorph': {
    marginBottom: '32px',
  },
  '.dashboard-header-neumorph h1': {
    fontSize: '2.25rem',
    fontWeight: 700,
    color: '#1a202c',
  },
  '.dashboard-header-neumorph p': {
    fontSize: '1rem',
    color: '#718096',
    marginTop: '4px',
  },
  '.kpi-card-final-compact, .main-chart-card-neumorph, .sellers-card-neumorph': {
    background: 'rgba(255, 255, 255, 0.6)',
    backdropFilter: 'blur(10px)',
    WebkitBackdropFilter: 'blur(10px)',
    borderRadius: '16px',
    border: '1px solid rgba(255, 255, 255, 0.25)',
    boxShadow: '0px 4px 20px rgba(0, 0, 0, 0.04)',
    transition: 'all 0.25s ease-in-out',
  },
  '.kpi-card-final-compact:hover, .main-chart-card-neumorph:hover, .sellers-card-neumorph:hover': {
    transform: 'translateY(-5px)',
    boxShadow: '0px 8px 25px rgba(0, 0, 0, 0.06)',
  },
  '.kpi-grid-neumorph': {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '20px',
    marginBottom: '32px',
  },
  '.kpi-card-final-compact': {
    display: 'flex',
    justifyContent: 'space-between',
    position: 'relative',
    overflow: 'hidden',
    padding: '16px',
  },
  '.kpi-border-neumorph': {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: '5px',
    backgroundColor: '#3b82f6',
    borderRadius: 0,
  },
  '.kpi-content-neumorph': {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    paddingLeft: '15px',
  },
  '.kpi-title-neumorph': {
    fontSize: '0.8rem',
    fontWeight: 500,
    color: '#4a5568',
    marginBottom: '4px',
  },
  '.kpi-value-neumorph': {
    fontSize: '1.4rem',
    fontWeight: 600,
    color: '#1a202c',
    marginBottom: '6px',
  },
  '.kpi-change-neumorph': {
    fontSize: '0.8rem',
    fontWeight: 500,
  },
  '.kpi-change-neumorph.positive': { color: '#10b981' },
  '.kpi-change-neumorph.negative': { color: '#ef4444' },
  '.kpi-chart-neumorph': {
    width: '70px',
    height: '45px',
    alignSelf: 'center',
    opacity: 0.8,
  },
  '.main-grid-neumorph': {
    display: 'grid',
    gridTemplateColumns: '2fr 1fr',
    gap: '24px',
  },
  '.main-chart-card-neumorph, .sellers-card-neumorph': {
    padding: '28px',
  },
  '.card-title-neumorph': {
    fontSize: '1.25rem',
    fontWeight: 600,
    color: '#2d3748',
    margin: '0 0 24px 0',
  },
  '.sellers-list-neumorph': {
    listStyle: 'none',
    padding: 0,
    margin: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
  },
  '.sellers-list-neumorph li': {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
  },
  '.seller-avatar-neumorph': {
    width: '40px',
    height: '40px',
    borderRadius: '50%',
  },
  '.seller-info-neumorph': {
    flexGrow: 1,
  },
  '.seller-info-neumorph span': {
    fontSize: '0.9rem',
    fontWeight: 500,
    color: '#2d3748',
    marginBottom: '8px',
    display: 'block',
  },
  '.seller-sales-neumorph': {
    fontSize: '0.9rem',
    fontWeight: 600,
    color: '#1a202c',
  },
  '.progress-bar-neumorph': {
    width: '100%',
    height: '8px',
    backgroundColor: 'rgba(0, 0, 0, 0.05)',
    borderRadius: '4px',
    overflow: 'hidden',
  },
  '.progress-neumorph': {
    height: '100%',
    backgroundColor: '#3b82f6',
    borderRadius: '4px',
  },
  '@media (max-width: 1200px)': {
    '.kpi-chart-neumorph': {
      display: 'none',
    },
  },
  '@media (max-width: 1024px)': {
    '.main-grid-neumorph': {
      gridTemplateColumns: '1fr',
    },
    '.kpi-grid-neumorph': {
      gridTemplateColumns: 'repeat(2, 1fr)',
    },
  },
  '@media (max-width: 640px)': {
    '.kpi-grid-neumorph': {
      gridTemplateColumns: '1fr',
    },
  },


  // =========================================================
  // --- ESTILOS DA PÁGINA DO CONTROLADOR (SEGUNDA CRIAÇÃO) ---
  // =========================================================
  
  controllerPageContainer: {
    fontFamily: "'Poppins', sans-serif",
    backgroundColor: '#f4f7fa',
    padding: '32px',
    minHeight: '100vh',
  },
  controllerPageHeader: {
    marginBottom: '40px',
  },
  headerH1: {
    fontSize: '2.5rem',
    fontWeight: '700',
    color: '#1a202c',
    margin: '0 0 8px 0',
  },
  headerP: {
    fontSize: '1rem',
    color: '#718096',
    margin: 0,
  },
  layoutFinal: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(380px, 1fr))',
    gap: '24px',
  },
  controllerCard: {
    background: 'rgba(255, 255, 255, 0.9)',
    backdropFilter: 'blur(10px)',
    WebkitBackdropFilter: 'blur(10px)',
    borderRadius: '16px',
    border: '1px solid rgba(0, 0, 0, 0.05)',
    boxShadow: '0 8px 32px 0 rgba(31, 38, 135, 0.07)',
    display: 'flex',
    flexDirection: 'column',
  },
  cardHeader: {
    display: 'flex',
    alignItems: 'center',
    padding: '20px 24px',
    borderBottom: '1px solid #e2e8f0',
  },
  cardHeaderIcon: {
    fontSize: '1.2rem',
    color: '#3b82f6',
    marginRight: '12px',
    width: '24px',
    textAlign: 'center',
  },
  cardHeaderH3: {
    fontSize: '1.25rem',
    fontWeight: '600',
    color: '#2d3748',
    margin: 0,
    flexGrow: 1,
  },
  cardBody: {
    padding: '24px',
    flexGrow: 1,
  },
  cardFooter: {
    padding: '20px 24px',
    borderTop: '1px solid #e2e8f0',
    textAlign: 'right',
    backgroundColor: 'rgba(248, 250, 252, 0.5)',
    borderBottomLeftRadius: '16px',
    borderBottomRightRadius: '16px',
  },
  formGroup: {
    marginBottom: '18px',
  },
  formGroupRow: {
    display: 'flex',
    gap: '16px',
    marginBottom: '18px',
  },
  formLabel: {
    display: 'block',
    fontSize: '0.875rem',
    fontWeight: '500',
    color: '#4a5568',
    marginBottom: '6px',
  },
  formInput: {
    width: '100%',
    padding: '10px 14px',
    fontSize: '0.95rem',
    border: '1px solid #cbd5e1',
    borderRadius: '8px',
    backgroundColor: '#fff',
    transition: 'border-color 0.2s, box-shadow 0.2s',
    boxSizing: 'border-box',
  },
  toggleWrapper: {
    paddingTop: '10px',
  },
  toggleWrapperSeparated: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    paddingTop: '10px',
  },
  toggleSwitchContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  toggleSwitch: {
    position: 'relative',
    display: 'inline-block',
    width: '44px',
    height: '22px',
  },
  toggleSwitchInput: {
    opacity: 0,
    width: 0,
    height: 0,
  },
  slider: {
    position: 'absolute',
    cursor: 'pointer',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#ccc',
    transition: '0.4s',
    borderRadius: '22px',
  },
  sliderBefore: {
    position: 'absolute',
    content: '""',
    height: '18px',
    width: '18px',
    left: '2px',
    bottom: '2px',
    backgroundColor: 'white',
    transition: '0.4s',
    borderRadius: '50%',
  },
  toggleSwitchContainerSpan: {
    fontWeight: 500,
    color: '#4a5568',
  },
  saveCardButton: {
    backgroundColor: '#3b82f6',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    padding: '10px 20px',
    fontSize: '0.9rem',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'background-color 0.2s, transform 0.1s',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
  },
  rulesManagementSection: {
    display: 'flex',
    gap: '12px',
    marginTop: '24px',
  },
  rulesBtn: {
    flex: 1,
    padding: '10px',
    border: '1px solid #cbd5e1',
    borderRadius: '8px',
    backgroundColor: 'white',
    cursor: 'pointer',
    fontWeight: 600,
    transition: 'all 0.2s',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
  },
  rulesBtnView: {
    color: '#4a5568',
  },
  rulesBtnViewActive: {
    backgroundColor: '#eef2ff',
    borderColor: '#3b82f6',
    color: '#3b82f6',
  },
  rulesBtnCreate: {
    color: '#16a34a',
    borderColor: '#86efac',
    backgroundColor: '#f0fdf4',
  },
  rulesListWrapper: {
    maxHeight: 0,
    overflow: 'hidden',
    transition: 'max-height 0.5s ease-in-out, margin-top 0.5s ease-in-out',
    marginTop: 0,
  },
  rulesListWrapperOpen: {
    maxHeight: '500px',
    marginTop: '24px',
  },
  rulesList: {
    border: '1px solid #e2e8f0',
    borderRadius: '8px',
    padding: '16px',
    backgroundColor: '#f8fafc',
  },
  rulesListH4: {
    margin: '0 0 16px 0',
    color: '#334155',
    fontWeight: 600,
  },
  rulesSearch: {
    width: '100%',
    padding: '8px 12px',
    border: '1px solid #cbd5e1',
    borderRadius: '6px',
    marginBottom: '16px',
    boxSizing: 'border-box',
  },
  rulesListUl: {
    listStyle: 'none',
    padding: 0,
    margin: 0,
  },
  rulesListItem: {
    display: 'flex',
    alignItems: 'center',
    padding: '12px 0',
    borderBottom: '1px solid #e2e8f0',
  },
  ruleName: {
    fontWeight: 500,
    color: '#1e293b',
    flexGrow: 1,
  },
  ruleDetails: {
    display: 'flex',
    gap: '16px',
    color: '#64748b',
    fontSize: '0.85rem',
    marginRight: '16px',
  },
  ruleActions: {
    display: 'flex',
    gap: '8px',
  },
  ruleActionButton: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: '#94a3b8',
    fontSize: '1rem',
    padding: '4px',
  },
  ruleActionButtonDanger: {
    color: '#ef4444',
  },
  paginationContainerRules: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: '16px',
    gap: '12px'
  },
  paginationRulesButton: {
    background: '#fff',
    border: '1px solid #cbd5e1',
    borderRadius: '6px',
    width: '30px',
    height: '30px',
    cursor: 'pointer',
  },
  paginationRulesSpan: {
    fontWeight: 500,
    color: '#475569'
  },
  createPageBtn: {
    background: 'none',
    border: 'none',
    color: '#3b82f6',
    fontSize: '1.2rem',
    cursor: 'pointer',
    padding: '4px 8px',
    borderRadius: '50%',
  },
  visiblePagesList: {
    listStyle: 'none',
    padding: 0,
    margin: 0,
  },
  visiblePagesListItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '14px 0',
    borderBottom: '1px solid #e2e8f0',
  },
  pageInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  pageInfoIcon: {
    color: '#64748b',
    width: '18px',
    textAlign: 'center',
  },
  pageInfoSpan: {
    fontWeight: 500,
    color: '#1e293b',
  },
  pageActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
  },
  pageActionButton: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: '#94a3b8',
    fontSize: '1rem',
    padding: '4px',
  },
  modalBackdrop: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(15, 23, 42, 0.5)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  },
  modalContent: {
    background: 'white',
    borderRadius: '16px',
    boxShadow: '0 10px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
    width: '90%',
    maxWidth: '500px',
    overflow: 'hidden',
  },
  modalHeaderCtrl: {
    padding: '20px 24px',
    borderBottom: '1px solid #e2e8f0',
  },
  modalHeaderCtrlH3: {
    margin: 0,
    fontSize: '1.25rem',
    fontWeight: 600,
    color: '#1e293b',
  },
  createRuleForm: {
    padding: '24px',
  },
  formGroupCentered: {
    display: 'flex',
    justifyContent: 'center',
    paddingTop: '10px',
  },
  modalFooterCtrl: {
    padding: '16px 24px',
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '12px',
    backgroundColor: '#f8fafc',
  },
  cancelBtnCtrl: {
    backgroundColor: 'white',
    color: '#475569',
    border: '1px solid #cbd5e1',
    borderRadius: '8px',
    padding: '10px 20px',
    fontSize: '0.9rem',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
  },
};

export default styles;