const styles = {
  detailPageContainer: {
    fontFamily: "'Poppins', sans-serif",
    background: "linear-gradient(120deg, #f8fafc, #f1f5f9)",
    padding: "32px",
    borderRadius: "24px",
  },
  detailHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "32px",
    paddingBottom: "24px",
    borderBottom: "1px solid #e2e8f0",
  },
  headerLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
  },
  backButton: {
    background: '#fff',
    border: '1px solid #e2e8f0',
    width: '40px',
    height: '40px',
    borderRadius: '12px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '1rem',
    color: '#4b5563',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  headerTitle: {
    margin: 0,
    fontSize: "2rem",
    fontWeight: 700,
    color: "#1e293b",
  },
  headerTitleId: {
    color: "#64748b",
    fontWeight: 500,
  },
  headerActions: {
    display: "flex",
    gap: "16px",
    alignItems: "center",
  },
  goToClientButton: {
    background: "#fff",
    color: "#475569",
    border: "1px solid #cbd5e1",
    borderRadius: "12px",
    padding: "10px 18px",
    fontWeight: 600,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    transition: "all 0.2s ease",
  },
  statusBadge: {
    padding: "8px 16px",
    borderRadius: "12px",
    fontSize: "0.8rem",
    fontWeight: 600,
    textTransform: "uppercase",
  },
  statusValorizando: { backgroundColor: "#def7ec", color: "#03543f" },
  statusPendente: { backgroundColor: "#fef3c7", color: "#92400e" },
  statusFinalizado: { backgroundColor: "#e5e7eb", color: "#4b5563" },
  statusCancelado: { backgroundColor: "#fee2e2", color: "#991b1b" },
  detailGrid: {
    display: "grid",
    gridTemplateColumns: "2fr 1fr",
    gap: "32px",
    alignItems: "flex-start",
  },
  mainContent: {
    display: "flex",
    flexDirection: "column",
    gap: "32px",
  },
  kpiGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "24px",
  },
  kpiCard: {
    background: "rgba(255, 255, 255, 0.7)",
    backdropFilter: "blur(10px)",
    borderRadius: "16px",
    padding: "24px",
    border: "1px solid #e2e8f0",
  },
  kpiCardTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    fontSize: "0.875rem",
    color: "#64748b",
    fontWeight: 500,
    margin: "0 0 8px 0",
  },
  kpiCardValue: {
    fontSize: "2rem",
    fontWeight: 700,
    color: "#0f172a",
    margin: 0,
  },
  progressSection: {
    background: "rgba(255, 255, 255, 0.7)",
    backdropFilter: "blur(10px)",
    borderRadius: "16px",
    padding: "24px",
    border: "1px solid #e2e8f0",
  },
  progressHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '16px'
  },
  progressTitle: {
    fontSize: "1.125rem",
    fontWeight: 600,
    color: "#1e293b",
    margin: 0
  },
  progressDates: {
    fontSize: '0.8rem',
    color: '#64748b'
  },
  progressBarContainer: {
    width: '100%',
    height: '10px',
    backgroundColor: '#e2e8f0',
    borderRadius: '5px',
    overflow: 'hidden',
    margin: '8px 0',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: '#3b82f6',
    borderRadius: '5px',
    transition: 'width 0.5s ease-in-out',
  },
  progressLabels: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '0.875rem',
    color: '#475569',
    fontWeight: 500,
  },
  actionPanel: {
    display: "flex",
    flexDirection: "column",
    gap: "24px",
    position: "sticky",
    top: "20px",
  },
  actionCard: {
    background: "rgba(255, 255, 255, 0.7)",
    backdropFilter: "blur(10px)",
    borderRadius: "16px",
    padding: "24px",
    border: "1px solid #e2e8f0",
  },
  actionCardTitle: {
    fontSize: "1.125rem",
    fontWeight: 600,
    color: "#1e293b",
    margin: "0 0 16px 0",
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  actionCardInputGroup: {
    display: "flex",
    gap: "12px",
    marginBottom: "16px",
  },
  actionCardInput: {
    flexGrow: 1,
    border: "1px solid #cbd5e1",
    borderRadius: "8px",
    padding: "10px 12px",
    fontSize: "0.9rem",
    fontFamily: "'Poppins', sans-serif",
    outline: "none",
  },
  actionCardButton: {
    border: "none",
    borderRadius: "8px",
    padding: "10px 16px",
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  buttonPrimary: {
    backgroundColor: "#3b82f6",
    color: "#fff",
  },
  buttonDanger: {
    width: "100%",
    backgroundColor: "#ef4444",
    color: "#fff",
    padding: "12px",
  },
  toggleSwitchContainer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  toggleLabel: {
    fontSize: '0.9rem',
    fontWeight: 500,
    color: '#334155',
  },
  toggleSwitch: {
    position: 'relative',
    display: 'inline-block',
    width: '50px',
    height: '28px',
  },
  toggleSwitchInput: {
    opacity: 0,
    width: 0,
    height: 0,
  },
  toggleSlider: {
    position: 'absolute',
    cursor: 'pointer',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#ccc',
    transition: '.4s',
    borderRadius: '28px',
  },
  toggleSliderBefore: {
    position: 'absolute',
    content: '""',
    height: '20px',
    width: '20px',
    left: '4px',
    bottom: '4px',
    backgroundColor: 'white',
    transition: '.4s',
    borderRadius: '50%',
  },
  toggleSwitchInputChecked: {
    backgroundColor: '#3b82f6',
  },
  toggleSwitchInputCheckedBefore: {
    transform: 'translateX(22px)',
  },
};

export default styles;