const styles = {
  detailPageContainer: {
    fontFamily: "'Poppins', sans-serif",
    background: "linear-gradient(120deg, #f8fafc, #f1f5f9)",
    padding: "32px",
    borderRadius: "24px",
  },
  detailHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "32px",
    paddingBottom: "24px",
    borderBottom: "1px solid #e2e8f0",
  },
  headerLeft: { display: "flex", alignItems: "center", gap: "16px" },
  backButton: {
    background: "#fff",
    border: "1px solid #e2e8f0",
    width: "40px",
    height: "40px",
    borderRadius: "12px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "1rem",
    color: "#4b5563",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  headerTitle: {
    margin: 0,
    fontSize: "2rem",
    fontWeight: 700,
    color: "#1e293b",
  },
  headerTitleId: { color: "#64748b", fontWeight: 500 },
  headerActions: { display: "flex", gap: "16px", alignItems: "center" },
  goToClientButton: {
    background: "#fff",
    color: "#475569",
    border: "1px solid #cbd5e1",
    borderRadius: "12px",
    padding: "10px 18px",
    fontWeight: 600,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    transition: "all 0.2s ease",
  },
  statusBadge: {
    padding: "8px 16px",
    borderRadius: "12px",
    fontSize: "0.8rem",
    fontWeight: 600,
    textTransform: "uppercase",
  },
  statusValorizando: { backgroundColor: "#def7ec", color: "#03543f" },
  statusPendente: { backgroundColor: "#fef3c7", color: "#92400e" },
  statusFinalizado: { backgroundColor: "#e5e7eb", color: "#4b5563" },
  statusCancelado: { backgroundColor: "#fee2e2", color: "#991b1b" },

  pendingActions: {
    display: "flex",
    gap: "12px",
  },
  actionButton: {
    border: "none",
    borderRadius: "12px",
    padding: "10px 18px",
    fontWeight: 600,
    fontSize: "0.9rem",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    transition: "all 0.2s ease",
  },
  approveBtn: {
    backgroundColor: "#10b981",
    color: "#fff",
  },
  denyBtn: {
    backgroundColor: "#ef4444",
    color: "#fff",
  },
  detailGrid: {
    display: "grid",
    gridTemplateColumns: "2fr 1fr",
    gap: "32px",
    alignItems: "flex-start",
  },
  mainContent: { display: "flex", flexDirection: "column", gap: "32px" },
  kpiGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "24px",
  },
  kpiCard: {
    background: "rgba(255, 255, 255, 0.7)",
    backdropFilter: "blur(10px)",
    borderRadius: "16px",
    padding: "24px",
    border: "1px solid #e2e8f0",
  },
  kpiCardTitle: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    fontSize: "0.875rem",
    color: "#64748b",
    fontWeight: 500,
    margin: "0 0 8px 0",
  },
  kpiCardValue: {
    fontSize: "2rem",
    fontWeight: 700,
    color: "#0f172a",
    margin: 0,
  },
  progressSection: {
    background: "rgba(255, 255, 255, 0.7)",
    backdropFilter: "blur(10px)",
    borderRadius: "16px",
    padding: "24px",
    border: "1px solid #e2e8f0",
  },
  progressHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "16px",
  },
  progressTitle: {
    fontSize: "1.125rem",
    fontWeight: 600,
    color: "#1e293b",
    margin: 0,
  },
  progressDates: { fontSize: "0.8rem", color: "#64748b" },
  progressBarContainer: {
    width: "100%",
    height: "10px",
    backgroundColor: "#e2e8f0",
    borderRadius: "5px",
    overflow: "hidden",
    margin: "8px 0",
  },
  progressBarFill: {
    height: "100%",
    backgroundColor: "#3b82f6",
    borderRadius: "5px",
    transition: "width 0.5s ease-in-out",
  },
  progressLabels: {
    display: "flex",
    justifyContent: "space-between",
    fontSize: "0.875rem",
    color: "#475569",
    fontWeight: 500,
  },
  actionPanel: {
    display: "flex",
    flexDirection: "column",
    gap: "24px",
    position: "sticky",
    top: "20px",
  },
  actionCard: {
    background: "rgba(255, 255, 255, 0.7)",
    backdropFilter: "blur(10px)",
    borderRadius: "16px",
    padding: "24px",
    border: "1px solid #e2e8f0",
  },
  infoCard: {
    background: "rgba(255, 255, 255, 0.7)",
    backdropFilter: "blur(10px)",
    borderRadius: "16px",
    padding: "24px",
    border: "1px solid #e2e8f0",
  },
  actionCardTitle: {
    fontSize: "1.125rem",
    fontWeight: 600,
    color: "#1e293b",
    margin: "0 0 16px 0",
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  infoCardTitle: {
    fontSize: "1.125rem",
    fontWeight: 600,
    color: "#1e293b",
    margin: "0",
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  actionCardInputGroup: { display: "flex", gap: "12px", marginBottom: "16px" },
  actionCardInput: {
    flexGrow: 1,
    border: "1px solid #cbd5e1",
    borderRadius: "8px",
    padding: "10px 12px",
    fontSize: "0.9rem",
    fontFamily: "'Poppins', sans-serif",
    outline: "none",
  },
  actionCardButton: {
    border: "none",
    borderRadius: "8px",
    padding: "10px 16px",
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.2s ease",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
  },
  buttonPrimary: { backgroundColor: "#3b82f6", color: "#fff" },
  buttonSecondary: {
    backgroundColor: "#fff",
    color: "#475569",
    border: "1px solid #cbd5e1",
  },
  buttonDanger: {
    width: "100%",
    backgroundColor: "#ef4444",
    color: "#fff",
    padding: "12px",
  },
  toggleSwitchContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  toggleLabel: { fontSize: "0.9rem", fontWeight: 500, color: "#334155" },
  toggleSwitch: {
    position: "relative",
    display: "inline-block",
    width: "50px",
    height: "28px",
  },
  toggleSwitchInput: { opacity: 0, width: 0, height: 0 },
  toggleSlider: {
    position: "absolute",
    cursor: "pointer",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#ccc",
    transition: ".4s",
    borderRadius: "28px",
  },
  toggleSliderBefore: {
    position: "absolute",
    content: '""',
    height: "20px",
    width: "20px",
    left: "4px",
    bottom: "4px",
    backgroundColor: "white",
    transition: ".4s",
    borderRadius: "50%",
  },
  toggleSwitchInputChecked: { backgroundColor: "#3b82f6" },
  toggleSwitchInputCheckedBefore: { transform: "translateX(22px)" },
  mediaGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(120px, 1fr))",
    gap: "16px",
    marginTop: "16px",
  },
  mediaItem: {
    position: "relative",
    paddingTop: "100%",
    borderRadius: "12px",
    overflow: "hidden",
    background: "#e2e8f0",
  },
  mediaContent: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  addMediaButton: {
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    border: "2px dashed #cbd5e1",
    borderRadius: "12px",
    background: "transparent",
    cursor: "pointer",
    color: "#64748b",
    fontSize: "0.9rem",
    gridColumn: "span 1",
    gridRow: "span 1",
    minHeight: "120px",
  },
  certificateList: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    marginTop: "16px",
  },
  certificateItem: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    background: "#f8fafc",
    padding: "8px",
    borderRadius: "8px",
    border: "1px solid #e2e8f0",
  },
  certificateImage: {
    width: "100%",
    height: "auto",
    borderRadius: "6px",
    objectFit: "cover",
  },
  certActionsContainer: { marginTop: "16px" },
  certOptionButtons: { display: "flex", alignItems: "center", gap: "12px" },
  certCancelButton: {
    background: "transparent",
    border: "none",
    color: "#94a3b8",
    fontSize: "1.2rem",
    cursor: "pointer",
    padding: "0 8px",
  },
  modalOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(15, 23, 42, 0.7)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
  },
  modalContent: {
    background: "white",
    padding: "32px",
    borderRadius: "16px",
    maxWidth: "500px",
    width: "100%",
    boxShadow: "0 10px 25px rgba(0,0,0,0.1)",
  },
  certificatePreview: {
    padding: "24px",
    borderRadius: "12px",
    border: "1px solid #e2e8f0",
    background: "linear-gradient(135deg, #f5f7fa, #eef2f7)",
    marginBottom: "24px",
  },
  certHeader: {
    textAlign: "center",
    borderBottom: "1px solid #d1d5db",
    paddingBottom: "16px",
    marginBottom: "16px",
  },
  certIcon: { fontSize: "2.5rem", color: "#3b82f6", marginBottom: "8px" },
  certTitle: {
    margin: 0,
    fontSize: "1.5rem",
    fontWeight: 700,
    color: "#1e293b",
  },
  certSubtitle: {
    margin: "4px 0 0",
    fontSize: "0.8rem",
    color: "#64748b",
    textTransform: "uppercase",
  },
  certBody: { margin: "16px 0" },
  certDetail: {
    display: "flex",
    justifyContent: "space-between",
    padding: "8px 0",
    borderBottom: "1px dotted #d1d5db",
  },
  certFooter: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: "16px",
    marginTop: "16px",
  },
  certSeal: {
    background: "#10b981",
    color: "white",
    padding: "8px 12px",
    borderRadius: "6px",
    fontSize: "0.8rem",
    fontWeight: "bold",
  },
  certForm: { display: "flex", flexDirection: "column", gap: "16px" },
  certFormActions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "12px",
    marginTop: "8px",
  },
  saveChangesButton: { backgroundColor: "#10b981", color: "#fff" },
  removeItemButton: {
    position: "absolute",
    top: "4px",
    right: "4px",
    background: "rgba(0,0,0,0.6)",
    color: "white",
    border: "none",
    borderRadius: "50%",
    width: "24px",
    height: "24px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 10,
    fontSize: "0.8rem",
    transition: "background-color 0.2s",
  },
  loadingOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(255, 255, 255, 0.8)",
    backdropFilter: "blur(5px)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 9999,
  },
  loadingSpinner: {
    border: "4px solid #f3f3f3",
    borderTop: "4px solid #3b82f6",
    borderRadius: "50%",
    width: "50px",
    height: "50px",
    animation: "spin 1s linear infinite",
  },
  loadingText: {
    marginTop: "20px",
    fontSize: "1.2rem",
    fontWeight: 600,
    color: "#1e293b",
  },
  buttonSpinner: {
    border: "2px solid rgba(255,255,255,0.3)",
    borderTop: "2px solid #fff",
    borderRadius: "50%",
    width: "16px",
    height: "16px",
    animation: "spin 1s linear infinite",
  },
  cardHeaderAction: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "16px",
  },
  deleteAllButton: {
    background: "#fee2e2",
    color: "#dc2626",
    border: "none",
    borderRadius: "6px",
    padding: "6px 12px",
    fontSize: "0.8rem",
    fontWeight: "600",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  modalTitle: {
    fontSize: "1.5rem",
    fontWeight: 600,
    color: "#1e293b",
    margin: "0 0 24px 0",
    textAlign: "center",
  },
  modalForm: { display: "flex", flexDirection: "column", gap: "16px" },
  modalSelectGroup: { display: "flex", flexDirection: "column", gap: "8px" },
  modalSelect: {
    border: "1px solid #cbd5e1",
    borderRadius: "8px",
    padding: "10px 12px",
    fontSize: "0.9rem",
    fontFamily: "'Poppins', sans-serif",
    outline: "none",
  },
  modalActions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "12px",
    marginTop: "16px",
  },
  trackingInfo: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    fontSize: "0.9rem",
  },
  editTrackingButton: {
    background: "none",
    border: "none",
    color: "#64748b",
    textDecoration: "underline",
    cursor: "pointer",
    padding: "8px 0 0",
    alignSelf: "flex-start",
    fontSize: "0.85rem",
  },
  toggleSpinner: {
    position: "absolute",
    top: "4px",
    left: "4px",
    border: "2px solid #e2e8f0",
    borderTop: "2px solid #3b82f6",
    borderRadius: "50%",
    width: "20px",
    height: "20px",
    animation: "spin 1s linear infinite",
  },
  // NOVO: Estilos para o Card de Pagamento
  paymentInfoContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    marginBottom: "16px",
  },
  paymentInfoRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    fontSize: "0.9rem",
  },
  paymentInfoLabel: {
    color: "#64748b",
    fontWeight: 500,
  },
  paymentStatusBadge: {
    padding: "4px 12px",
    borderRadius: "10px",
    fontSize: "0.8rem",
    fontWeight: 600,
    textTransform: "uppercase",
  },
  paymentStatusReceived: { backgroundColor: "#def7ec", color: "#03543f" },
  paymentStatusPending: { backgroundColor: "#fef3c7", color: "#92400e" },
  paymentStatusOverdue: { backgroundColor: "#fee2e2", color: "#991b1b" },
  paymentStatusCancelled: { backgroundColor: "#e5e7eb", color: "#4b5563" },
  approvePaymentButton: {
    width: "100%",
    backgroundColor: "#22c55e",
    color: "#fff",
  },
  // Fim dos novos estilos

  "@keyframes spin": {
    "0%": { transform: "rotate(0deg)" },
    "100%": { transform: "rotate(360deg)" },
  },
};

export default styles;
