const styles = {
  modalBackdrop: {
    position: "fixed",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    backgroundColor: "rgba(0, 0, 0, 0.3)",
    backdropFilter: "blur(8px)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  modalContent: {
    background: "rgba(249, 250, 251, 0.95)",
    borderRadius: "20px",
    padding: "28px",
    width: "90%",
    maxWidth: "400px",
  },
  modalHeader: { marginBottom: "24px" },
  modalTitle: {
    fontSize: "1.5rem",
    fontWeight: 600,
    color: "#1f2937",
    margin: 0,
    textAlign: "center",
  },
  formGroup: { display: "flex", flexDirection: "column", gap: "8px" },
  formLabel: { fontSize: "0.9rem", fontWeight: 500, color: "#4b5563" },
  formInput: {
    width: "100%",
    boxSizing: "border-box",
    fontSize: "1rem",
    color: "#2d3748",
    background: "#fff",
    padding: "12px 14px",
    borderRadius: "8px",
    border: "1px solid #d1d5db",
  },
  modalFooter: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "12px",
    marginTop: "28px",
    paddingTop: "20px",
    borderTop: "1px solid #e5e7eb",
  },
  button: {
    border: "none",
    borderRadius: "10px",
    padding: "10px 20px",
    fontWeight: 600,
    cursor: "pointer",
  },
  cancelButton: { background: "#e5e7eb", color: "#374151" },
  saveButton: { background: "#10b981", color: "#ffffff" },
};
export default styles;
