const styles = {
    detailPageContainer: {
      fontFamily: "'Poppins', sans-serif",
      background: "linear-gradient(120deg, #f8fafc, #f1f5f9)",
      padding: "32px",
      borderRadius: "24px",
    },
    detailHeader: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: "32px",
      paddingBottom: "24px",
      borderBottom: "1px solid #e2e8f0",
    },
    headerLeft: {
      display: 'flex',
      alignItems: 'center',
      gap: '16px',
    },
    backButton: {
      background: '#fff',
      border: '1px solid #e2e8f0',
      width: '40px',
      height: '40px',
      borderRadius: '12px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      fontSize: '1rem',
      color: '#4b5563',
      cursor: 'pointer',
      transition: 'all 0.2s ease',
    },
    headerTitle: { margin: 0, fontSize: "2rem", fontWeight: 700, color: "#1e293b" },
    headerTitleId: { color: "#64748b", fontWeight: 500 },
    headerActions: { display: "flex", gap: "16px", alignItems: "center" },
    statusBadge: { padding: "8px 16px", borderRadius: "12px", fontSize: "0.8rem", fontWeight: 600, textTransform: "uppercase" },
    statusPendente: { backgroundColor: "#fef3c7", color: "#92400e" },
    statusAprovado: { backgroundColor: "#def7ec", color: "#03543f" },
    statusCancelado: { backgroundColor: "#fee2e2", color: "#991b1b" },
    
    detailGrid: {
      display: "grid",
      gridTemplateColumns: "2fr 1fr",
      gap: "32px",
      alignItems: "flex-start",
    },
    mainContent: { display: "flex", flexDirection: "column", gap: "32px" },
    infoCard: {
      background: "rgba(255, 255, 255, 0.7)",
      backdropFilter: "blur(10px)",
      borderRadius: "16px",
      padding: "24px",
      border: "1px solid #e2e8f0",
    },
    infoCardTitle: {
      fontSize: "1.125rem",
      fontWeight: 600,
      color: "#1e293b",
      margin: "0 0 16px 0",
      display: "flex",
      alignItems: "center",
      gap: "10px",
    },
    kpiGrid: { display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: "24px" },
    kpiItem: { textAlign: "center" },
    kpiLabel: { fontSize: "0.875rem", color: "#64748b", margin: "0 0 4px 0" },
    kpiValue: { fontSize: "1.75rem", fontWeight: 700, color: "#0f172a", margin: 0 },
    
    infoList: { listStyle: "none", padding: 0, margin: 0, display: "flex", flexDirection: "column", gap: "12px" },
    infoItem: { display: "flex", justifyContent: "space-between", alignItems: "center" },
    infoLabel: { color: "#64748b" },
    infoValue: { fontWeight: 600, color: "#1e293b" },
  
    actionPanel: { position: "sticky", top: "20px" },
    actionCard: {
      background: "rgba(255, 255, 255, 0.7)",
      backdropFilter: "blur(10px)",
      borderRadius: "16px",
      padding: "24px",
      border: "1px solid #e2e8f0",
      display: "flex",
      flexDirection: "column",
      gap: "16px",
    },
    actionCardTitle: {
      fontSize: "1.125rem",
      fontWeight: 600,
      color: "#1e293b",
      margin: "0 0 8px 0",
      paddingBottom: "8px",
      borderBottom: "1px solid #e2e8f0",
    },
    actionButton: {
      border: "none",
      borderRadius: "10px",
      padding: "12px",
      fontWeight: 600,
      cursor: "pointer",
      transition: "all 0.2s ease",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      gap: "8px",
      fontSize: "0.9rem",
    },
    payAndTransferButton: { backgroundColor: "#10b981", color: "#fff" },
    markAsPaidButton: { backgroundColor: "#3b82f6", color: "#fff" },
    cancelButton: { backgroundColor: "#ef4444", color: "#fff" },
    disabledButton: { backgroundColor: "#d1d5db", color: "#6b7280", cursor: "not-allowed" },
  
    processedInfo: { textAlign: "center", color: "#4b5563" },
  };
  
  export default styles;