const styles = {
    // Estilos da Página Principal
    contractsPageContainer: { fontFamily: "'Poppins', sans-serif" },
    contractsPageHeader: { marginBottom: '24px' },
    contractsPageHeaderH1: { fontSize: '2.25rem', fontWeight: 700, color: '#1a202c' },
    contractKpiCard: { background: 'rgba(255, 255, 255, 0.6)', backdropFilter: 'blur(10px)', WebkitBackdropFilter: 'blur(10px)', borderRadius: '16px', border: '1px solid rgba(255, 255, 255, 0.25)', boxShadow: '0px 4px 20px rgba(0, 0, 0, 0.04)', padding: '24px', display: 'flex', alignItems: 'center', gap: '24px', marginBottom: '32px' },
    kpiTotal: { textAlign: 'center' },
    kpiTotalP: { margin: '0 0 8px 0', fontSize: '1rem', color: '#4a5568', fontWeight: 500 },
    kpiTotalSpan: { fontSize: '2.5rem', fontWeight: 700, color: '#1a202c' },
    kpiDivider: { width: '1px', backgroundColor: '#e5e7eb', alignSelf: 'stretch' },
    kpiStatusBreakdown: { display: 'flex', flexGrow: 1, justifyContent: 'space-around' },
    statusItem: { textAlign: 'center' },
    statusItemSpan: { fontSize: '1.5rem', fontWeight: 600, color: '#2d3748' },
    statusItemP: { margin: '4px 0 0 0', fontSize: '0.8rem', color: '#718096' },
    tableControlsHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px', gap: '16px' },
    searchBox: { flexGrow: 1, display: 'flex', alignItems: 'center', background: '#fff', borderRadius: '12px', padding: '0 16px', border: '1px solid #e5e7eb', boxShadow: '0px 4px 20px rgba(0, 0, 0, 0.04)' },
    searchBoxIcon: { color: '#9ca3af' },
    searchInput: { flexGrow: 1, border: 'none', outline: 'none', padding: '12px 8px', background: 'transparent', fontFamily: "'Poppins', sans-serif", fontSize: '0.9rem' },
    filters: { display: 'flex', gap: '12px' },
    contractsTableCard: { background: 'rgba(255, 255, 255, 0.6)', backdropFilter: 'blur(10px)', WebkitBackdropFilter: 'blur(10px)', borderRadius: '16px', border: '1px solid rgba(255, 255, 255, 0.25)', boxShadow: '0px 4px 20px rgba(0, 0, 0, 0.04)', padding: '16px', overflowX: 'auto' },
    contractsTable: { width: '100%', borderCollapse: 'collapse' },
    tableHeader: { fontSize: '0.75rem', color: '#6b7280', textTransform: 'uppercase', fontWeight: 600, letterSpacing: '0.05em' },
    tableCell: { padding: '16px 20px', textAlign: 'left', borderBottom: '1px solid #f3f4f6', fontSize: '0.9rem', color: '#2d3748', fontWeight: 500 },
    tableRow: { cursor: 'pointer', transition: 'background-color 0.2s' },
    tableRowHover: { backgroundColor: 'rgba(255, 255, 255, 0.7)' },
    statusBadge: { padding: '4px 10px', borderRadius: '12px', fontSize: '0.75rem', fontWeight: 600, textTransform: 'uppercase' },
    statusValorizando: { backgroundColor: '#def7ec', color: '#03543f' },
    statusPendente: { backgroundColor: '#fef3c7', color: '#92400e' },
    statusFinalizado: { backgroundColor: '#e5e7eb', color: '#4b5563' },
    paginationContainer: { display: 'flex', justifyContent: 'center', alignItems: 'center', padding: '24px 0 8px 0', gap: '16px' },
    paginationSpan: { fontSize: '0.9rem', color: '#6b7280' },
    paginationButton: { backgroundColor: '#fff', border: '1px solid #e5e7eb', color: '#374151', padding: '8px 16px', borderRadius: '8px', cursor: 'pointer', transition: 'all 0.2s' },
    paginationButtonHover: { backgroundColor: '#f3f4f6', borderColor: '#d1d5db' },
    paginationButtonDisabled: { opacity: 0.5, cursor: 'not-allowed' },

    // Estilos do Modal
    modalBackdrop: { position: 'fixed', top: 0, left: 0, width: '100%', height: '100%', backgroundColor: 'rgba(0, 0, 0, 0.2)', backdropFilter: 'blur(8px)', WebkitBackdropFilter: 'blur(8px)', display: 'flex', justifyContent: 'center', alignItems: 'center', zIndex: 1000 },
    modalContent: { background: 'rgba(249, 250, 251, 0.9)', borderRadius: '20px', border: '1px solid rgba(255, 255, 255, 0.3)', boxShadow: '0 10px 30px rgba(0,0,0,0.1)', padding: '28px', position: 'relative', width: '90%', maxWidth: '950px', maxHeight: '90vh', overflowY: 'auto' },
    modalHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px' },
    modalHeaderH2: { fontSize: '1.75rem', color: '#1a202c', margin: 0 },
    loginAsClientButton: { backgroundColor: '#f59e0b', color: '#fff', fontWeight: 600, border: 'none', borderRadius: '12px', padding: '10px 16px', display: 'flex', alignItems: 'center', gap: '8px', cursor: 'pointer', transition: 'all 0.2s' },
    detailGrid: { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '20px', paddingBottom: '24px', borderBottom: '1px solid #e5e7eb', marginBottom: '24px' },
    detailItemSpan: { display: 'block', fontSize: '0.8rem', color: '#6b7280', marginBottom: '4px', textTransform: 'uppercase', fontWeight: 500 },
    detailItemP: { fontSize: '0.95rem', color: '#2d3748', fontWeight: 500, margin: 0, background: '#fff', padding: '10px 12px', borderRadius: '8px', border: '1px solid #e5e7eb', wordBreak: 'break-all' },
    detailItemFullWidth: { gridColumn: '1 / -1' },
    detailSelect: { width: '100%', fontSize: '0.95rem', color: '#2d3748', fontWeight: 500, margin: 0, background: '#fff', padding: '10px 12px', borderRadius: '8px', border: '1px solid #e5e7eb', fontFamily: "'Poppins', sans-serif", cursor: 'pointer' },
    actionSectionsGrid: { display: 'grid', gridTemplateColumns: '1fr 1.5fr', gap: '24px' },
    actionSectionH4: { fontSize: '1rem', fontWeight: 600, color: '#4b5563', margin: '0 0 12px 0' },
    actionInputGroup: { display: 'flex', flexDirection: 'column', gap: '12px' },
    actionInputGroupSingle: { flexDirection: 'row' },
    actionInput: { width: '100%', boxSizing: 'border-box', fontSize: '0.9rem', color: '#2d3748', background: '#fff', padding: '10px 12px', borderRadius: '8px', border: '1px solid #e5e7eb' },
    actionButton: { backgroundColor: '#10b981', color: '#fff', border: 'none', padding: '10px', borderRadius: '8px', fontWeight: 500, cursor: 'pointer' },
    modalFooter: { marginTop: '32px', display: 'flex', gap: '16px', justifyContent: 'flex-end' },
    modalActionButton: { border: 'none', borderRadius: '12px', padding: '12px 20px', fontWeight: 500, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '8px', transition: 'all 0.2s' },
    modalActionButtonPrimary: { backgroundColor: '#3b82f6', color: '#fff' },
    modalCloseButton: { background: '#e5e7eb', color: '#374151', border: 'none', borderRadius: '12px', padding: '12px 20px', fontWeight: 500 },
    
    // Dropdown
    customDropdownContainer: { position: 'relative' },
    dropdownHeader: { background: '#fff', border: '1px solid #e5e7eb', borderRadius: '12px', padding: '12px 16px', fontFamily: "'Poppins', sans-serif", fontSize: '0.9rem', cursor: 'pointer', display: 'flex', justifyContent: 'space-between', alignItems: 'center', width: '200px', textAlign: 'left' },
    dropdownHeaderIcon: { transition: 'transform 0.2s ease', color: '#9ca3af' },
    dropdownHeaderIconOpen: { transform: 'rotate(180deg)' },
    dropdownList: { position: 'absolute', top: '110%', right: 0, width: '100%', background: '#fff', borderRadius: '8px', border: '1px solid #e5e7eb', boxShadow: '0 10px 20px rgba(0,0,0,0.07)', listStyle: 'none', padding: '8px', margin: 0, zIndex: 10 },
    dropdownListItem: { padding: '8px 12px', borderRadius: '6px', cursor: 'pointer' },
    dropdownListItemHover: { backgroundColor: '#f3f4f6' },
};

export default styles;