const styles = {
  // Estilos Gerais da Página
  clientsPageContainer: {
    fontFamily: "'Poppins', sans-serif",
    width: "100%",
    padding: "24px",
    boxSizing: "border-box",
    backgroundColor: "#f9fafb",
  },
  clientsPageHeader: {
    marginBottom: "24px",
    width: "100%",
  },
  clientsPageHeaderH1: {
    fontSize: "2.25rem",
    fontWeight: 700,
    color: "#1a202c",
  },

  // Controles da Tabela (ÁREA MELHORADA COM ORDENAÇÃO)
  tableControlsHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    gap: "16px",
    marginBottom: "24px",
  },
  leftControls: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
    flexWrap: "wrap",
    flexGrow: 1,
  },
  searchBox: {
    display: "flex",
    alignItems: "center",
    position: "relative",
    flexGrow: 1,
    minWidth: "250px",
    maxWidth: "450px",
  },
  searchBoxIcon: {
    position: "absolute",
    left: "14px",
    color: "#9ca3af",
    fontSize: "0.9rem",
  },
  searchInput: {
    width: "100%",
    border: "1px solid #e5e7eb",
    borderRadius: "12px",
    padding: "12px 12px 12px 40px",
    fontFamily: "'Poppins', sans-serif",
    fontSize: "0.9rem",
    color: "#374151",
    outline: "none",
    transition: "border-color 0.2s, box-shadow 0.2s",
    boxShadow: "0 1px 2px rgba(0,0,0,0.05)",
  },
  // NOVOS ESTILOS PARA ORDENAÇÃO
  sortContainer: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  sortSelect: {
    fontFamily: "'Poppins', sans-serif",
    fontSize: "0.9rem",
    padding: "11px 16px",
    border: "1px solid #e5e7eb",
    borderRadius: "12px",
    backgroundColor: "#fff",
    color: "#374151",
    cursor: "pointer",
    outline: "none",
    boxShadow: "0 1px 2px rgba(0,0,0,0.05)",
  },
  sortDirectionButton: {
    backgroundColor: "#fff",
    border: "1px solid #e5e7eb",
    color: "#374151",
    borderRadius: "12px",
    width: "42px",
    height: "42px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    transition: "background-color 0.2s, border-color 0.2s",
    boxShadow: "0 1px 2px rgba(0,0,0,0.05)",
  },
  // FIM DOS NOVOS ESTILOS
  addClientButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    backgroundColor: "#3b82f6",
    color: "#fff",
    border: "none",
    borderRadius: "12px",
    padding: "12px 20px",
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.2s ease-in-out",
    boxShadow: "0 1px 3px rgba(0,0,0,0.1)",
  },
  addClientButtonHover: {
    backgroundColor: "#2563eb",
    transform: "translateY(-2px)",
    boxShadow: "0 4px 10px rgba(59, 130, 246, 0.3)",
  },

  // Estilos da Tabela de Clientes
  clientsTableCard: {
    background: "#ffffff",
    borderRadius: "16px",
    boxShadow: "0px 4px 20px rgba(0, 0, 0, 0.05)",
    padding: "16px",
    overflowX: "auto",
  },
  clientsTable: {
    width: "100%",
    borderCollapse: "collapse",
  },
  tableHeader: {
    fontSize: "0.75rem",
    color: "#6b7280",
    textTransform: "uppercase",
    fontWeight: 600,
    letterSpacing: "0.05em",
  },
  tableCell: {
    padding: "16px 20px",
    textAlign: "left",
    borderBottom: "1px solid #f3f4f6",
    fontSize: "0.9rem",
    color: "#2d3748",
    fontWeight: 500,
    verticalAlign: "middle",
  },
  tableRow: {
    cursor: "pointer",
    transition: "background-color 0.2s",
  },
  tableRowHover: {
    backgroundColor: "#f9fafb",
  },
  tableAvatar: {
    width: "40px",
    height: "40px",
    borderRadius: "50%",
    objectFit: "cover",
  },
  emailCell: {
    maxWidth: "250px",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },

  // Estilos de Paginação
  paginationContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "24px 0 8px 0",
    gap: "16px",
  },
  paginationSpan: {
    fontSize: "0.9rem",
    color: "#6b7280",
  },
  paginationButton: {
    backgroundColor: "#fff",
    border: "1px solid #e5e7eb",
    color: "#374151",
    padding: "8px 16px",
    borderRadius: "8px",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  paginationButtonHover: {
    backgroundColor: "#f3f4f6",
    borderColor: "#d1d5db",
  },
  paginationButtonDisabled: {
    opacity: 0.5,
    cursor: "not-allowed",
  },

  // Estilos do Modal
  modalBackdrop: {
    position: "fixed",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    backgroundColor: "rgba(0, 0, 0, 0.2)",
    backdropFilter: "blur(8px)",
    WebkitBackdropFilter: "blur(8px)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
    animation: "fadeIn 0.3s ease",
  },
  modalContentLarge: {
    width: "90%",
    maxWidth: "1100px",
    background: "rgba(249, 250, 251, 0.9)",
    borderRadius: "20px",
    border: "1px solid rgba(255, 255, 255, 0.3)",
    boxShadow: "0 10px 30px rgba(0,0,0,0.1)",
    padding: "32px",
    position: "relative",
    animation: "scaleUp 0.3s ease",
    maxHeight: "90vh",
    overflowY: "auto",
  },
  modalHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "28px",
  },
  modalHeaderH2: {
    fontSize: "1.75rem",
    color: "#1a202c",
    margin: 0,
  },
  loginAsClientButton: {
    backgroundColor: "#f59e0b",
    color: "#fff",
    fontWeight: 600,
    border: "none",
    borderRadius: "12px",
    padding: "10px 16px",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  loginAsClientButtonHover: {
    backgroundColor: "#d97706",
    transform: "translateY(-2px)",
  },
  detailGridV2: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "20px",
  },
  detailItemV2Label: {
    display: "block",
    fontSize: "0.8rem",
    color: "#6b7280",
    marginBottom: "4px",
    textTransform: "uppercase",
    fontWeight: 500,
  },
  detailItemV2Input: {
    fontSize: "0.95rem",
    color: "#2d3748",
    fontWeight: 500,
    margin: 0,
    background: "#fff",
    padding: "10px 12px",
    borderRadius: "8px",
    border: "1px solid #e5e7eb",
    width: "100%",
    boxSizing: "border-box",
    fontFamily: "'Poppins', sans-serif",
  },
  detailItemV2InputDisabled: {
    background: "#f9fafb",
    color: "#6b7280",
    borderColor: "#f3f4f6",
  },
  modalFooter: {
    marginTop: "32px",
    display: "flex",
    gap: "16px",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  modalActionButton: {
    border: "none",
    borderRadius: "12px",
    padding: "12px 20px",
    fontWeight: 500,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    transition: "all 0.2s",
  },
  modalActionButtonPrimary: {
    backgroundColor: "#3b82f6",
    color: "#fff",
  },
  modalActionButtonSave: {
    backgroundColor: "#10b981",
    color: "#fff",
  },
  modalActionButtonCancel: {
    backgroundColor: "#f3f4f6",
    color: "#4b5563",
    border: "1px solid #d1d5db",
  },
  modalCloseButton: {
    background: "#e5e7eb",
    color: "#374151",
    border: "none",
    borderRadius: "12px",
    padding: "12px 20px",
    fontWeight: 500,
  },
  contractsSection: {
    marginTop: "24px",
    border: "1px solid #e5e7eb",
    borderRadius: "12px",
    background: "#fff",
  },
  contractsSectionHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "16px",
    cursor: "pointer",
  },
  headerInfo: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  headerInfoIcon: {
    fontSize: "1.2rem",
    color: "#3b82f6",
  },
  headerInfoH4: {
    margin: 0,
    fontSize: "1rem",
    fontWeight: 600,
    color: "#2d3748",
  },
  toggleArrow: {
    transition: "transform 0.3s ease",
  },
  toggleArrowOpen: {
    transform: "rotate(180deg)",
  },
  contractsListContainer: {
    maxHeight: 0,
    overflow: "hidden",
    transition: "max-height 0.4s ease-in-out",
  },
  contractsListContainerOpen: {
    maxHeight: "300px",
  },
  contractListSearch: {
    padding: "0 16px 16px 16px",
    position: "relative",
  },
  contractListSearchIcon: {
    position: "absolute",
    left: "26px",
    top: "35%",
    transform: "translateY(-50%)",
    color: "#9ca3af",
  },
  contractListSearchInput: {
    width: "100%",
    boxSizing: "border-box",
    border: "1px solid #e5e7eb",
    borderRadius: "8px",
    padding: "8px 8px 8px 32px",
  },
  contractList: {
    listStyle: "none",
    padding: "0 16px 16px 16px",
    margin: 0,
    maxHeight: "200px",
    overflowY: "auto",
  },
  contractListItem: {
    display: "flex",
    justifyContent: "space-between",
    padding: "12px",
    borderRadius: "8px",
  },
  contractListItemOdd: {
    backgroundColor: "#f9fafb",
  },
  balanceSection: {
    marginTop: "24px",
    paddingTop: "24px",
    borderTop: "1px solid #e5e7eb",
  },
  balanceInfo: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  balanceValue: {
    color: "#10b981",
    fontSize: "1.25rem",
    fontWeight: 700,
    background: "transparent",
    border: "none",
    padding: "10px 0",
  },
  addBalanceButton: {
    backgroundColor: "#f3f4f6",
    border: "1px solid #d1d5db",
    color: "#374151",
    borderRadius: "12px",
    padding: "10px 16px",
    fontWeight: 500,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    transition: "all 0.2s",
  },
  addBalanceButtonHover: {
    backgroundColor: "#e5e7eb",
  },
  addBalanceForm: {
    maxHeight: 0,
    overflow: "hidden",
    transition: "max-height 0.4s ease-in-out, margin-top 0.4s ease-in-out",
    display: "flex",
    gap: "16px",
  },
  addBalanceFormOpen: {
    maxHeight: "100px",
    marginTop: "16px",
  },
  addBalanceFormInput: {
    flexGrow: 1,
    background: "#fff",
    border: "1px solid #e5e7eb",
    borderRadius: "8px",
    padding: "10px 12px",
    fontFamily: "'Poppins', sans-serif",
  },
  addBalanceFormButton: {
    backgroundColor: "#10b981",
    color: "#fff",
    border: "none",
    borderRadius: "8px",
    padding: "10px 20px",
    fontWeight: 500,
    cursor: "pointer",
  },
};

export default styles;
