const styles = {
  clientsPageContainer: { fontFamily: "'Poppins', sans-serif", width: "100%" },
  clientsPageHeader: { marginBottom: "24px", width: "100%"  },
  clientsPageHeaderH1: {
    fontSize: "2.25rem",
    fontWeight: 700,
    color: "#1a202c",
  },
  clientKpiCards: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
    gap: "24px",
    marginBottom: "32px",
    width: "100%" 
  },
  clientKpiCard: {
    background: "rgba(255, 255, 255, 0.6)",
    backdropFilter: "blur(10px)",
    WebkitBackdropFilter: "blur(10px)",
    borderRadius: "16px",
    border: "1px solid rgba(255, 255, 255, 0.25)",
    boxShadow: "0px 4px 20px rgba(0, 0, 0, 0.04)",
    padding: "24px",
    display: "flex",
    alignItems: "center",
    gap: "20px",
  },
  clientKpiCardIcon: {
    fontSize: "1.5rem",
    color: "#3b82f6",
    backgroundColor: "rgba(59, 130, 246, 0.1)",
    width: "48px",
    height: "48px",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  clientKpiCardH4: {
    margin: "0 0 4px 0",
    fontSize: "0.9rem",
    fontWeight: 500,
    color: "#4a5568",
  },
  kpiMainValue: {
    fontSize: "1.75rem",
    fontWeight: 700,
    color: "#1a202c",
    margin: 0,
  },
  tableControlsHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "24px",
  },
  actionsGroup: { display: "flex", gap: "16px" },
  searchBox: {
    display: "flex",
    alignItems: "center",
    background: "#fff",
    borderRadius: "12px",
    padding: "0 16px",
    border: "1px solid #e5e7eb",
    boxShadow: "0px 4px 20px rgba(0, 0, 0, 0.04)",
  },
  searchBoxIcon: { color: "#9ca3af" },
  searchInput: {
    border: "none",
    outline: "none",
    padding: "12px 8px",
    background: "transparent",
    width: "250px",
    fontFamily: "'Poppins', sans-serif",
    fontSize: "0.9rem",
    color: "#374151",
  },
  filterBox: {
    display: "flex",
    alignItems: "center",
    background: "#fff",
    borderRadius: "12px",
    padding: "0 16px",
    border: "1px solid #e5e7eb",
    boxShadow: "0px 4px 20px rgba(0, 0, 0, 0.04)",
  },
  filterSelect: {
    border: "none",
    outline: "none",
    padding: "12px 8px",
    background: "transparent",
    width: "auto",
    fontFamily: "'Poppins', sans-serif",
    fontSize: "0.9rem",
    color: "#374151",
    cursor: "pointer",
    WebkitAppearance: "none",
    MozAppearance: "none",
    appearance: "none",
    paddingRight: "30px",
    backgroundImage:
      "url('data:image/svg+xml;charset=US-ASCII,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22292.4%22%20height%3D%22292.4%22%3E%3Cpath%20fill%3D%22%239CA3AF%22%20d%3D%22M287%2069.4a17.6%2017.6%200%200%200-13-5.4H18.4c-5%200-9.3%201.8-12.9%205.4A17.6%2017.6%200%200%200%200%2082.2c0%205%201.8%209.3%205.4%2012.9l128%20127.9c3.6%203.6%207.8%205.4%2012.8%205.4s9.2-1.8%2012.8-5.4L287%2095c3.5-3.5%205.4-7.8%205.4-12.8%200-5-1.9-9.2-5.5-12.8z%22/%3E%3C/svg%3E')",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "right 12px top 50%",
    backgroundSize: ".65em auto",
  },
  addClientButton: {
    backgroundColor: "#3b82f6",
    color: "#fff",
    border: "none",
    borderRadius: "12px",
    padding: "12px 20px",
    fontWeight: 500,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    transition: "all 0.2s",
  },
  addClientButtonHover: {
    backgroundColor: "#2563eb",
    transform: "translateY(-2px)",
    boxShadow: "0 4px 10px rgba(59, 130, 246, 0.3)",
  },
  clientsTableCard: {
    background: "rgba(255, 255, 255, 0.6)",
    backdropFilter: "blur(10px)",
    WebkitBackdropFilter: "blur(10px)",
    borderRadius: "16px",
    border: "1px solid rgba(255, 255, 255, 0.25)",
    boxShadow: "0px 4px 20px rgba(0, 0, 0, 0.04)",
    padding: "16px",
    overflowX: "auto",
  },
  clientsTable: { width: "100%", borderCollapse: "collapse" },
  tableHeader: {
    fontSize: "0.75rem",
    color: "#6b7280",
    textTransform: "uppercase",
    fontWeight: 600,
    letterSpacing: "0.05em",
  },
  tableCell: {
    padding: "16px 20px",
    textAlign: "left",
    borderBottom: "1px solid #f3f4f6",
    fontSize: "0.9rem",
    color: "#2d3748",
    fontWeight: 500,
    verticalAlign: "middle",
  },
  tableRow: { cursor: "pointer", transition: "background-color 0.2s" },
  tableRowHover: { backgroundColor: "rgba(255, 255, 255, 0.7)" },
  tableAvatar: {
    width: '40px',
    height: '40px',
    borderRadius: '50%',
    objectFit: 'cover',
  },
  emailCell: {
    maxWidth: "250px",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  paginationContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "24px 0 8px 0",
    gap: "16px",
  },
  paginationSpan: { fontSize: "0.9rem", color: "#6b7280" },
  paginationButton: {
    backgroundColor: "#fff",
    border: "1px solid #e5e7eb",
    color: "#374151",
    padding: "8px 16px",
    borderRadius: "8px",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  paginationButtonHover: { backgroundColor: "#f3f4f6", borderColor: "#d1d5db" },
  paginationButtonDisabled: { opacity: 0.5, cursor: "not-allowed" },
  modalBackdrop: {
    position: "fixed",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    backgroundColor: "rgba(0, 0, 0, 0.2)",
    backdropFilter: "blur(8px)",
    WebkitBackdropFilter: "blur(8px)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
    animation: "fadeIn 0.3s ease",
  },
  modalContentLarge: {
    width: "90%",
    maxWidth: "1100px",
    background: "rgba(249, 250, 251, 0.9)",
    borderRadius: "20px",
    border: "1px solid rgba(255, 255, 255, 0.3)",
    boxShadow: "0 10px 30px rgba(0,0,0,0.1)",
    padding: "32px",
    position: "relative",
    animation: "scaleUp 0.3s ease",
    maxHeight: "90vh",
    overflowY: "auto",
  },
  modalHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "28px",
  },
  modalHeaderH2: { fontSize: "1.75rem", color: "#1a202c", margin: 0 },
  loginAsClientButton: {
    backgroundColor: "#f59e0b",
    color: "#fff",
    fontWeight: 600,
    border: "none",
    borderRadius: "12px",
    padding: "10px 16px",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  loginAsClientButtonHover: {
    backgroundColor: "#d97706",
    transform: "translateY(-2px)",
  },
  detailGridV2: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "20px",
  },
  detailItemV2Label: {
    display: "block",
    fontSize: "0.8rem",
    color: "#6b7280",
    marginBottom: "4px",
    textTransform: "uppercase",
    fontWeight: 500,
  },
  detailItemV2Input: {
    fontSize: "0.95rem",
    color: "#2d3748",
    fontWeight: 500,
    margin: 0,
    background: "#fff",
    padding: "10px 12px",
    borderRadius: "8px",
    border: "1px solid #e5e7eb",
    width: "100%",
    boxSizing: "border-box",
    fontFamily: "'Poppins', sans-serif",
  },
  detailItemV2InputDisabled: {
    background: "#f9fafb",
    color: "#6b7280",
    borderColor: "#f3f4f6",
  },
  modalFooter: {
    marginTop: "32px",
    display: "flex",
    gap: "16px",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  modalActionButton: {
    border: "none",
    borderRadius: "12px",
    padding: "12px 20px",
    fontWeight: 500,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    transition: "all 0.2s",
  },
  modalActionButtonPrimary: { backgroundColor: "#3b82f6", color: "#fff" },
  modalActionButtonSave: { backgroundColor: "#10b981", color: "#fff" },
  modalActionButtonCancel: {
    backgroundColor: "#f3f4f6",
    color: "#4b5563",
    border: "1px solid #d1d5db",
  },
  modalCloseButton: {
    background: "#e5e7eb",
    color: "#374151",
    border: "none",
    borderRadius: "12px",
    padding: "12px 20px",
    fontWeight: 500,
  },
  contractsSection: {
    marginTop: "24px",
    border: "1px solid #e5e7eb",
    borderRadius: "12px",
    background: "#fff",
  },
  contractsSectionHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "16px",
    cursor: "pointer",
  },
  headerInfo: { display: "flex", alignItems: "center", gap: "12px" },
  headerInfoIcon: { fontSize: "1.2rem", color: "#3b82f6" },
  headerInfoH4: {
    margin: 0,
    fontSize: "1rem",
    fontWeight: 600,
    color: "#2d3748",
  },
  toggleArrow: { transition: "transform 0.3s ease" },
  toggleArrowOpen: { transform: "rotate(180deg)" },
  contractsListContainer: {
    maxHeight: 0,
    overflow: "hidden",
    transition: "max-height 0.4s ease-in-out",
  },
  contractsListContainerOpen: { maxHeight: "300px" },
  contractListSearch: { padding: "0 16px 16px 16px", position: "relative" },
  contractListSearchIcon: {
    position: "absolute",
    left: "26px",
    top: "35%",
    transform: "translateY(-50%)",
    color: "#9ca3af",
  },
  contractListSearchInput: {
    width: "100%",
    boxSizing: "border-box",
    border: "1px solid #e5e7eb",
    borderRadius: "8px",
    padding: "8px 8px 8px 32px",
  },
  contractList: {
    listStyle: "none",
    padding: "0 16px 16px 16px",
    margin: 0,
    maxHeight: "200px",
    overflowY: "auto",
  },
  contractListItem: {
    display: "flex",
    justifyContent: "space-between",
    padding: "12px",
    borderRadius: "8px",
  },
  contractListItemOdd: { backgroundColor: "#f9fafb" },
  balanceSection: {
    marginTop: "24px",
    paddingTop: "24px",
    borderTop: "1px solid #e5e7eb",
  },
  balanceInfo: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  balanceValue: {
    color: "#10b981",
    fontSize: "1.25rem",
    fontWeight: 700,
    background: "transparent",
    border: "none",
    padding: "10px 0",
  },
  addBalanceButton: {
    backgroundColor: "#f3f4f6",
    border: "1px solid #d1d5db",
    color: "#374151",
    borderRadius: "12px",
    padding: "10px 16px",
    fontWeight: 500,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    transition: "all 0.2s",
  },
  addBalanceButtonHover: { backgroundColor: "#e5e7eb" },
  addBalanceForm: {
    maxHeight: 0,
    overflow: "hidden",
    transition: "max-height 0.4s ease-in-out, margin-top 0.4s ease-in-out",
    display: "flex",
    gap: "16px",
  },
  addBalanceFormOpen: { maxHeight: "100px", marginTop: "16px" },
  addBalanceFormInput: {
    flexGrow: 1,
    background: "#fff",
    border: "1px solid #e5e7eb",
    borderRadius: "8px",
    padding: "10px 12px",
    fontFamily: "'Poppins', sans-serif",
  },
  addBalanceFormButton: {
    backgroundColor: "#10b981",
    color: "#fff",
    border: "none",
    borderRadius: "8px",
    padding: "10px 20px",
    fontWeight: 500,
    cursor: "pointer",
  },
};

export default styles;