const colors = {
    primary: "#3b82f6",
    primaryDark: "#2563eb",
    background: "#f8f9fa",
    white: "#fff",
    textDark: "#1f2937",
    textLight: "#6b7280",
    border: "#d1d5db",
    borderLight: "#e5e7eb",
    shadow: "rgba(0, 0, 0, 0.05)",
    error: "#ef4444",
    success: "#10b981",
  };
  
  const styles = {
    pageContainer: {
      display: "flex",
      justifyContent: "center",
      width: '100%',
      padding: "20px",
      fontFamily: "'Poppins', sans-serif",
    },
    formContainer: {
      width: "100%",
      maxWidth: "850px",
      backgroundColor: colors.white,
      borderRadius: "16px",
      boxShadow: `0 10px 30px ${colors.shadow}`,
      padding: "40px 50px",
      boxSizing: "border-box",
    },
    progressBarContainer: {
      position: "relative",
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: "40px",
      width: "80%",
      margin: "0 auto 40px auto",
    },
    progressLine: {
      position: "absolute",
      top: "50%",
      left: 0,
      transform: "translateY(-50%)",
      height: "4px",
      backgroundColor: colors.borderLight,
      width: "100%",
      zIndex: 1,
    },
    progressLineActive: {
      position: "absolute",
      top: "50%",
      left: 0,
      transform: "translateY(-50%)",
      height: "4px",
      backgroundColor: colors.primary,
      zIndex: 2,
      transition: "width 0.4s ease-in-out",
    },
    progressStep: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      zIndex: 3,
      position: "relative",
      background: colors.white,
      padding: '0 10px'
    },
    progressCircle: (isActive, isCompleted) => ({
      height: "30px",
      width: "30px",
      borderRadius: "50%",
      backgroundColor: isCompleted ? colors.primary : colors.white,
      border: `3px solid ${isActive || isCompleted ? colors.primary : colors.borderLight}`,
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      color: isCompleted ? colors.white : isActive ? colors.primary : colors.textLight,
      fontWeight: "bold",
      transition: "all 0.4s",
    }),
    progressLabel: (isActive) => ({
      marginTop: "10px",
      fontSize: "0.9rem",
      fontWeight: isActive ? "bold" : "normal",
      color: isActive ? colors.primary : colors.textLight,
      transition: "all 0.4s",
    }),
    formTitle: {
      textAlign: "center",
      fontSize: "2rem",
      fontWeight: "600",
      color: colors.textDark,
      marginBottom: "10px",
    },
    formSubtitle: {
      textAlign: "center",
      fontSize: "0.95rem",
      color: colors.textLight,
      marginBottom: "30px",
    },
    formRow: {
      display: "flex",
      gap: "20px",
      marginBottom: "20px",
    },
    formField: {
      flex: 1,
    },
    label: {
      display: "block",
      fontSize: "0.9rem",
      color: colors.textLight,
      marginBottom: "5px",
      fontWeight: "500",
    },
    input: {
      width: "100%",
      padding: "12px 15px",
      fontSize: "1rem",
      border: `1px solid ${colors.border}`,
      borderRadius: "8px",
      boxSizing: "border-box",
      transition: "border-color 0.3s, box-shadow 0.3s",
      outline: "none",
      color: colors.textDark,
    },
    formNavigation: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      marginTop: "40px",
      borderTop: `1px solid ${colors.borderLight}`,
      paddingTop: '20px'
    },
    navButton: {
      padding: "12px 30px",
      border: `1px solid ${colors.border}`,
      backgroundColor: colors.white,
      color: colors.textDark,
      borderRadius: "8px",
      fontSize: "1rem",
      fontWeight: "bold",
      cursor: "pointer",
      transition: "all 0.3s",
    },
    submitButton: {
      padding: "12px 30px",
      backgroundColor: colors.primary,
      color: colors.white,
      border: "none",
      borderRadius: "8px",
      fontSize: "1rem",
      fontWeight: "bold",
      cursor: "pointer",
      transition: "background-color 0.3s, opacity 0.3s",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      gap: "10px",
      minWidth: "150px",
      minHeight: "48px",
    },
    errorMessage: {
      color: colors.error,
      fontSize: "0.9rem",
      textAlign: "center",
      marginBottom: "15px",
      minHeight: "20px",
    },
  };
  
  export default styles;