const styles = {
  offersPageContainer: {
    fontFamily: "'Poppins', sans-serif",
    backgroundColor: "#f8fafc",
    padding: "2rem",
    position: "relative",
  },
  offersPageHeader: { marginBottom: "2rem" },
  headerH1: { fontSize: "2.25rem", fontWeight: 700, color: "#1a202c" },
  headerP: { color: "#718096", marginTop: "4px" },

  loadingOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(248, 250, 252, 0.8)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
    backdropFilter: "blur(4px)",
    borderRadius: "16px",
    transition: "opacity 0.3s ease-in-out",
  },
  spinner: {
    width: "50px",
    height: "50px",
    border: "5px solid #e2e8f0",
    borderTop: "5px solid #4f46e5",
    borderRadius: "50%",
    animation: "spin 1s linear infinite",
  },

  viewToggleContainer: {
    display: "flex",
    marginBottom: "2rem",
    backgroundColor: "#fff",
    borderRadius: "12px",
    padding: "6px",
    border: "1px solid #e2e8f0",
    maxWidth: "500px",
  },
  toggleButton: {
    flex: 1,
    padding: "10px 20px",
    border: "none",
    backgroundColor: "transparent",
    borderRadius: "8px",
    cursor: "pointer",
    fontWeight: "600",
    color: "#475569",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    transition: "all 0.2s ease-in-out",
  },
  toggleButtonActive: {
    flex: 1,
    padding: "10px 20px",
    border: "none",
    backgroundColor: "#4f46e5",
    borderRadius: "8px",
    cursor: "pointer",
    fontWeight: "600",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    boxShadow: "0 4px 6px -1px rgba(0,0,0,0.1), 0 2px 4px -2px rgba(0,0,0,0.1)",
    transition: "all 0.2s ease-in-out",
  },

  offerCreationCard: {
    background: "#ffffff",
    borderRadius: "16px",
    border: "1px solid #e2e8f0",
    boxShadow: "0 4px 6px -1px rgba(0,0,0,0.1), 0 2px 4px -2px rgba(0,0,0,0.1)",
    marginBottom: "32px",
    overflow: "hidden",
    animation: "fadeIn 0.5s ease",
    position: "relative",
  },
  creationCardGrid: {
    display: "grid",
    gridTemplateColumns: "1.2fr 1fr",
    alignItems: "stretch",
  },
  offerFormSection: {
    display: "flex",
    flexDirection: "column",
    padding: "1.5rem",
  },
  offerPreviewSection: {
    backgroundColor: "#f1f5f9",
    padding: "1.5rem",
    borderLeft: "1px solid #e2e8f0",
    display: "flex",
    flexDirection: "column",
  },

  formSection: { marginBottom: "24px" },
  formSectionTitle: {
    fontSize: "1rem",
    fontWeight: 600,
    color: "#475569",
    borderBottom: "1px solid #e2e8f0",
    paddingBottom: "8px",
    marginBottom: "16px",
  },
  radioGroup: {
    display: "flex",
    gap: "20px",
    marginTop: "8px",
    flexWrap: "wrap",
  },
  radioLabel: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    cursor: "pointer",
    fontSize: "0.9rem",
  },
  formTextarea: { resize: "vertical", minHeight: "80px" },

  cardHeaderNoBorder: { padding: "0 0 1.5rem 0", borderBottom: "none" },
  cardHeaderIcon: { fontSize: "1.2rem", color: "#3b82f6" },
  cardHeaderH3: {
    margin: 0,
    fontSize: "1.25rem",
    fontWeight: 600,
    color: "#1a202c",
  },
  cardBody: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    flexGrow: 1,
    overflowY: "auto",
  },
  formGroup: { display: "flex", flexDirection: "column", marginBottom: "1rem" },
  formLabel: {
    fontSize: "0.85rem",
    fontWeight: 500,
    color: "#4a5568",
    marginBottom: "8px",
  },
  formInput: {
    fontFamily: "'Poppins', sans-serif",
    fontSize: "0.9rem",
    padding: "10px 12px",
    border: "1px solid #d1d5db",
    borderRadius: "8px",
    backgroundColor: "#fff",
    transition: "border-color 0.2s, box-shadow 0.2s",
  },
  cardFooter: {
    paddingTop: "1.5rem",
    borderTop: "1px solid #e2e8f0",
    display: "flex",
    justifyContent: "flex-end",
    marginTop: "auto",
  },
  saveOfferButton: {
    backgroundColor: "#4f46e5",
    color: "#fff",
    border: "none",
    borderRadius: "12px",
    padding: "12px 24px",
    fontSize: "1rem",
    fontWeight: 600,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "10px",
    transition: "all 0.2s",
    minWidth: "200px",
  },
  saveOfferButtonDisabled: {
    backgroundColor: "#a5b4fc",
    cursor: "not-allowed",
  },

  previewArea: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexGrow: 1,
    minHeight: "200px",
  },
  previewCard: {
    width: "100%",
    maxWidth: "350px",
    aspectRatio: "16 / 10",
    borderRadius: "12px",
    overflow: "hidden",
    position: "relative",
    boxShadow:
      "0 10px 15px -3px rgba(0,0,0,0.1), 0 4px 6px -4px rgba(0,0,0,0.1)",
    backgroundColor: "#e2e8f0",
  },
  previewMedia: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  previewTextOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    background: "linear-gradient(to top, rgba(0,0,0,0.8), transparent)",
    padding: "2rem 1rem 1rem 1rem",
    color: "#fff",
  },
  previewTitle: { margin: "0 0 4px 0", fontSize: "1.2rem", fontWeight: "bold" },
  previewDescription: {
    margin: 0,
    fontSize: "0.85rem",
    opacity: 0.9,
    lineHeight: 1.4,
  },
  placeholderPreview: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    color: "#9ca3af",
    textAlign: "center",
    width: "100%",
    height: "100%",
  },
  placeholderPreviewIcon: { fontSize: "3rem", marginBottom: "16px" },

  imagePreviewContainer: {
    position: "relative",
    width: "100px",
    height: "100px",
  },
  imagePreview: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    borderRadius: "8px",
  },
  deletePreviewButton: {
    position: "absolute",
    top: "-10px",
    right: "-10px",
    background: "#ef4444",
    color: "white",
    border: "2px solid white",
    borderRadius: "50%",
    width: "28px",
    height: "28px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 2px 4px rgba(0,0,0,0.2)",
  },
};

export default styles;