// CatalogStyle.js

const styles = {
  // --- Estrutura Principal ---
  catalogPageContainer: {
    fontFamily: "'Poppins', sans-serif",
    width: "100%",
    padding: "24px",
    boxSizing: "border-box",
    backgroundColor: "#f9fafb",
  },
  catalogPageHeader: {
    marginBottom: "24px",
  },
  catalogPageHeaderH1: {
    fontSize: "2.25rem",
    fontWeight: 700,
    color: "#1a202c",
  },

  // --- Controles (Busca, Filtro, Botão) ---
  controlsHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    gap: "16px",
    marginBottom: "24px",
  },
  leftControls: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
    flexWrap: "wrap",
    flexGrow: 1,
  },
  searchBox: {
    display: "flex",
    alignItems: "center",
    position: "relative",
    flexGrow: 1,
    minWidth: "250px",
    maxWidth: "400px",
  },
  searchIcon: {
    position: "absolute",
    left: "14px",
    color: "#9ca3af",
  },
  searchInput: {
    width: "100%",
    border: "1px solid #e5e7eb",
    borderRadius: "12px",
    padding: "12px 12px 12px 40px",
    fontFamily: "'Poppins', sans-serif",
    fontSize: "0.9rem",
    color: "#374151",
    outline: "none",
    transition: "border-color 0.2s, box-shadow 0.2s",
    boxShadow: "0 1px 2px rgba(0,0,0,0.05)",
  },
  filterSelect: {
    fontFamily: "'Poppins', sans-serif",
    fontSize: "0.9rem",
    padding: "11px 16px",
    border: "1px solid #e5e7eb",
    borderRadius: "12px",
    backgroundColor: "#fff",
    color: "#374151",
    cursor: "pointer",
    outline: "none",
    boxShadow: "0 1px 2px rgba(0,0,0,0.05)",
    minWidth: "150px",
  },
  addProductButton: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    backgroundColor: "#3b82f6",
    color: "#fff",
    border: "none",
    borderRadius: "12px",
    padding: "12px 20px",
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.2s ease-in-out",
    boxShadow: "0 1px 3px rgba(0,0,0,0.1)",
  },
  addProductButtonHover: {
    backgroundColor: "#2563eb",
    transform: "translateY(-2px)",
    boxShadow: "0 4px 10px rgba(59, 130, 246, 0.3)",
  },

  // --- Tabela de Produtos ---
  tableCard: {
    background: "#ffffff",
    borderRadius: "16px",
    boxShadow: "0px 4px 20px rgba(0, 0, 0, 0.05)",
    padding: "16px",
    overflowX: "auto",
  },
  productsTable: {
    width: "100%",
    borderCollapse: "collapse",
    minWidth: "600px",
  },
  tableCell: {
    padding: "16px 20px",
    textAlign: "left",
    borderBottom: "1px solid #f3f4f6",
    fontSize: "0.9rem",
    color: "#2d3748",
    fontWeight: 500,
    verticalAlign: "middle",
  },
  tableRow: {
    cursor: "pointer",
    transition: "background-color 0.2s",
  },
  tableRowHover: {
    backgroundColor: "#f9fafb",
  },
  productImageThumb: {
    width: "48px",
    height: "48px",
    borderRadius: "8px",
    objectFit: "cover",
  },
  statusBadge: {
    padding: "4px 10px",
    borderRadius: "12px",
    fontSize: "0.8rem",
    fontWeight: 600,
    textTransform: "capitalize",
  },
  statusAtivo: {
    color: "#166534",
    backgroundColor: "#dcfce7",
  },
  statusInativo: {
    color: "#7f1d1d",
    backgroundColor: "#fee2e2",
  },

  // --- Paginação ---
  paginationContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "24px 0 8px 0",
    gap: "16px",
  },
  paginationButton: {
    backgroundColor: "#fff",
    border: "1px solid #e5e7eb",
    color: "#374151",
    padding: "8px 16px",
    borderRadius: "8px",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  paginationButtonDisabled: {
    opacity: 0.5,
    cursor: "not-allowed",
  },
  paginationSpan: {
    fontSize: "0.9rem",
    color: "#6b7280",
  },

  // --- Estilos do Modal (genérico) ---
  modalBackdrop: {
    position: "fixed",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    backgroundColor: "rgba(17, 24, 39, 0.4)",
    backdropFilter: "blur(8px)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  modalContent: {
    background: "#ffffff",
    borderRadius: "20px",
    boxShadow: "0 10px 30px rgba(0,0,0,0.1)",
    padding: "32px",
    position: "relative",
    width: "90%",
    maxWidth: "600px",
    maxHeight: "90vh",
    overflowY: "auto",
  },
  modalCloseButton: {
    position: "absolute",
    top: "16px",
    right: "16px",
    background: "#f3f4f6",
    border: "none",
    borderRadius: "50%",
    width: "36px",
    height: "36px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    color: "#4b5563",
    fontSize: "1rem",
  },
  modalHeader: {
    marginBottom: "24px",
  },
  modalTitle: {
    fontSize: "1.5rem",
    fontWeight: 700,
    color: "#1a202c",
    margin: 0,
  },
  modalFooter: {
    marginTop: "32px",
    display: "flex",
    gap: "12px",
    justifyContent: "flex-end",
  },
  modalButton: {
    border: "none",
    borderRadius: "12px",
    padding: "12px 20px",
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.2s",
  },
  modalButtonPrimary: {
    backgroundColor: "#3b82f6",
    color: "#fff",
  },
  modalButtonSecondary: {
    backgroundColor: "#f3f4f6",
    color: "#4b5563",
    border: "1px solid #d1d5db",
  },
  modalButtonDanger: {
    backgroundColor: "#ef4444",
    color: "#fff",
  },

  // --- Estilos da Galeria de Imagens no Modal de Detalhes ---
  detailImageContainer: {
    position: "relative",
    width: "100%",
    marginBottom: "20px",
  },
  detailImage: {
    width: "100%",
    height: "300px",
    borderRadius: "16px",
    objectFit: "cover",
    backgroundColor: "#f3f4f6",
  },
  galleryArrow: {
    position: "absolute",
    top: "50%",
    transform: "translateY(-50%)",
    backgroundColor: "rgba(255, 255, 255, 0.8)",
    border: "1px solid #e5e7eb",
    borderRadius: "50%",
    width: "40px",
    height: "40px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    color: "#1f2937",
    fontSize: "1rem",
    transition: "all 0.2s",
  },
  galleryArrowLeft: {
    left: "12px",
  },
  galleryArrowRight: {
    right: "12px",
  },
  galleryArrowDisabled: {
    opacity: 0.4,
    cursor: "not-allowed",
  },
  galleryCounter: {
    position: "absolute",
    top: "12px",
    right: "12px",
    backgroundColor: "rgba(17, 24, 39, 0.7)",
    color: "#fff",
    padding: "4px 10px",
    borderRadius: "12px",
    fontSize: "0.8rem",
    fontWeight: 500,
  },

  detailGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "16px",
    marginBottom: "16px",
  },
  detailItem: {
    fontSize: "0.9rem",
  },
  detailLabel: {
    display: "block",
    color: "#6b7280",
    marginBottom: "4px",
    fontSize: "0.8rem",
  },
  detailValue: {
    color: "#1a202c",
    fontWeight: 500,
  },
  detailDescription: {
    gridColumn: "1 / -1",
  },

  // --- Estilos do Formulário de Adicionar/Editar ---
  formGroup: {
    marginBottom: "16px",
  },
  formLabel: {
    display: "block",
    marginBottom: "8px",
    color: "#374151",
    fontWeight: 500,
    fontSize: "0.9rem",
  },
  formInput: {
    width: "100%",
    boxSizing: "border-box",
    border: "1px solid #d1d5db",
    borderRadius: "12px",
    padding: "12px",
    fontSize: "0.9rem",
    fontFamily: "'Poppins', sans-serif",
  },
  formTextarea: {
    minHeight: "100px",
    resize: "vertical",
  },

  // --- ESTILOS PARA UPLOAD DE IMAGEM NO MODAL DE ADICIONAR (NOVO) ---
  imageUploadContainer: {
    marginTop: "8px",
  },
  uploadButton: {
    width: "100%",
    padding: "12px",
    border: "2px dashed #d1d5db",
    borderRadius: "12px",
    backgroundColor: "#f9fafb",
    color: "#374151",
    fontWeight: 500,
    cursor: "pointer",
    textAlign: "center",
    transition: "border-color 0.2s, background-color 0.2s",
  },
  imagePreviewGrid: {
    marginTop: "16px",
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(100px, 1fr))",
    gap: "12px",
  },
  imagePreviewItem: {
    position: "relative",
    width: "100%",
    paddingTop: "100%", // Mantém o aspect ratio 1:1
    borderRadius: "12px",
    overflow: "hidden",
    border: "1px solid #e5e7eb",
  },
  previewImage: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  removeImageButton: {
    position: "absolute",
    top: "6px",
    right: "6px",
    background: "rgba(255, 255, 255, 0.9)",
    border: "none",
    borderRadius: "50%",
    width: "24px",
    height: "24px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    color: "#374151",
    fontSize: "0.8rem",
    boxShadow: "0 1px 3px rgba(0,0,0,0.1)",
  },
};

export default styles;
