const styles = {
    loginContainer: {
        display: 'flex',
        width: '100vw',
        height: '100vh',
        fontFamily: "'Segoe UI', 'Roboto', sans-serif",
    },
    loginBranding: {
        flex: 1,
        background: 'linear-gradient(135deg, #2c3e50, #1a1d24)',
        color: '#ffffff',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        padding: '40px',
        textAlign: 'center',
    },
    brandingContent: {
        maxWidth: '400px',
    },
    brandingIcon: {
        fontSize: '80px',
        marginBottom: '24px',
        opacity: 0.8,
    },
    brandingH1: {
        fontSize: '3rem',
        margin: '0 0 16px 0',
        fontWeight: 700,
        letterSpacing: '2px',
    },
    brandingP: {
        fontSize: '1.1rem',
        lineHeight: 1.6,
        opacity: 0.9,
    },
    loginFormArea: {
        flex: 1,
        backgroundColor: '#ffffff',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        padding: '40px',
        position: 'relative', // Essencial para o overlay
    },
    loginForm: {
        width: '100%',
        maxWidth: '400px',
        padding: '40px',
        background: '#ffffff',
        borderRadius: '12px',
        boxShadow: '0 10px 30px rgba(0, 0, 0, 0.1)',
        transition: 'filter 0.3s ease-in-out',
    },
    loginFormH2: {
        color: '#333',
        fontSize: '2rem',
        fontWeight: 600,
        marginBottom: '8px',
        textAlign: 'center',
    },
    formSubtitle: {
        color: '#555',
        marginBottom: '32px',
        textAlign: 'center',
    },
    inputGroup: {
        position: 'relative',
        marginBottom: '24px',
    },
    inputIcon: {
        position: 'absolute',
        left: '15px',
        top: '50%',
        transform: 'translateY(-50%)',
        color: '#ccc',
        transition: 'color 0.3s ease',
    },
    inputField: {
        width: '100%',
        padding: '14px 45px 14px 45px',
        boxSizing: 'border-box',
        border: '1px solid #ccc',
        borderRadius: '8px',
        fontSize: '1rem',
        transition: 'border-color 0.3s ease',
    },
    inputFieldFocus: {
        outline: 'none',
        borderColor: '#007bff',
    },
    inputIconFocus: {
        color: '#007bff',
    },
    passwordToggleIcon: {
        position: 'absolute',
        right: '15px',
        top: '50%',
        transform: 'translateY(-50%)',
        color: '#ccc',
        cursor: 'pointer',
    },
    loginButton: {
        width: '100%',
        padding: '15px',
        backgroundColor: '#007bff',
        color: '#ffffff',
        border: 'none',
        borderRadius: '8px',
        fontSize: '1.1rem',
        fontWeight: 600,
        cursor: 'pointer',
        transition: 'background-color 0.3s ease',
        marginTop: '24px',
    },
    loginButtonHover: {
        backgroundColor: '#0056b3',
    },
    errorMessage: {
        color: '#d93025',
        background: '#fbe9e7',
        textAlign: 'center',
        padding: '10px',
        borderRadius: '8px',
        marginBottom: '16px',
        fontSize: '0.9rem',
    },

    // --- ESTILOS DO LOADING FANTÁSTICO ---
    loadingOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(255, 255, 255, 0.8)',
        backdropFilter: 'blur(5px)',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 10,
        borderRadius: '12px', // Para cobrir a área do formulário
    },
    loadingIcon: {
        fontSize: '60px',
        color: '#007bff',
        animation: 'pulse 1.5s infinite ease-in-out',
    },
    loadingText: {
        marginTop: '20px',
        color: '#0056b3',
        fontSize: '1.1rem',
        fontWeight: 500,
    },
    '@keyframes pulse': {
        '0%': { transform: 'scale(1)', opacity: 1 },
        '50%': { transform: 'scale(1.2)', opacity: 0.7 },
        '100%': { transform: 'scale(1)', opacity: 1 },
    },
};

export default styles;