const style = {
    profileContainer: {
        width: '100%',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        padding: '20px',
        fontFamily: "'Poppins', sans-serif",
    },
    pageTitle: {
        fontSize: '2rem',
        fontWeight: 600,
        color: '#333',
        marginBottom: '25px',
    },
    profileCard: {
        width: '100%',
        maxWidth: '800px',
        background: '#fff',
        borderRadius: '12px',
        boxShadow: '0 4px 15px rgba(0,0,0,0.08)',
        overflow: 'hidden',
    },
    cardHeader: {
        display: 'flex',
        alignItems: 'center',
        padding: '30px',
        backgroundColor: '#f8f9fa',
        borderBottom: '1px solid #e9ecef',
        gap: '20px'
    },
    avatar: {
        width: '80px',
        height: '80px',
        borderRadius: '50%',
        backgroundColor: '#122C4F',
        color: '#fff',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: '2.5rem',
        fontWeight: 'bold',
        flexShrink: 0,
    },
    userInfo: {
        display: 'flex',
        flexDirection: 'column',
        flexGrow: 1,
    },
    userName: {
        fontSize: '1.8rem',
        fontWeight: 600,
        color: '#122C4F',
        margin: 0,
    },
    userRole: {
        fontSize: '1rem',
        color: '#555',
        margin: '5px 0 0 0',
    },
    editButton: {
        background: 'transparent',
        color: '#3b82f6',
        border: `1px solid #3b82f6`,
        borderRadius: '8px',
        padding: '10px 20px',
        fontSize: '0.9rem',
        fontWeight: 500,
        cursor: 'pointer',
        transition: 'all 0.2s ease',
    },
    cardBody: {
        padding: '30px',
    },
    infoGrid: {
        display: 'grid',
        gridTemplateColumns: '1fr 1fr',
        gap: '25px',
    },
    infoItem: {
        display: 'flex',
        flexDirection: 'column',
    },
    infoLabel: {
        fontSize: '0.9rem',
        color: '#6c757d',
        marginBottom: '8px',
        fontWeight: '600',
    },
    inputBase: {
        width: '100%',
        padding: '12px 16px',
        fontSize: '1rem',
        border: `1px solid #e5e7eb`,
        borderRadius: '8px',
        backgroundColor: '#fff',
        color: '#111827',
        outline: 'none',
        transition: 'border-color 0.2s ease, box-shadow 0.2s ease',
        fontFamily: "'Poppins', sans-serif",
    },
    inputReadOnly: {
        backgroundColor: 'transparent',
        border: '1px solid transparent',
        paddingLeft: 0,
        color: '#333',
        cursor: 'default',
    },
    statusBadge: { 
        padding: '5px 12px', 
        borderRadius: '15px', 
        fontSize: '0.85rem', 
        fontWeight: 500, 
        color: '#fff', 
        width: 'fit-content',
    },
    statusActive: { 
        backgroundColor: '#28a745',
    },
    statusInactive: {
        backgroundColor: '#dc3545',
    },
    cardFooter: {
        display: 'flex',
        justifyContent: 'flex-end',
        gap: '16px',
        padding: '20px 30px',
        backgroundColor: '#f8f9fa',
        borderTop: `1px solid #e9ecef`,
    },
    cancelButton: {
        background: '#fff',
        color: '#6b7280',
        border: `1px solid #e5e7eb`,
        borderRadius: '8px',
        padding: '10px 20px',
        fontSize: '0.9rem',
        fontWeight: 500,
        cursor: 'pointer',
        transition: 'all 0.2s ease',
    },
    saveButton: {
        background: '#3b82f6',
        color: '#fff',
        border: 'none',
        borderRadius: '8px',
        padding: '10px 20px',
        fontSize: '0.9rem',
        fontWeight: 500,
        cursor: 'pointer',
        transition: 'all 0.2s ease',
    },
};

export default style;