const styles = {
  pageContainer: {
    fontFamily: "'Poppins', sans-serif",
    maxWidth: "900px",
    margin: "40px auto 0px auto",
  },
  header: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
    marginBottom: "32px",
  },
  backButton: {
    background: "#fff",
    border: "1px solid #e2e8f0",
    width: "40px",
    height: "40px",
    borderRadius: "12px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "1rem",
    color: "#4b5563",
    cursor: "pointer",
  },
  headerTitle: {
    fontSize: "2rem",
    fontWeight: 700,
    color: "#1e293b",
    margin: 0,
  },
  formCard: {
    background: "rgba(255, 255, 255, 0.7)",
    backdropFilter: "blur(10px)",
    borderRadius: "16px",
    padding: "28px",
    border: "1px solid #e2e8f0",
  },
  formGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "20px" },
  formGroup: { display: "flex", flexDirection: "column" },
  fullWidth: { gridColumn: "1 / -1" },
  formLabel: {
    fontSize: "0.8rem",
    color: "#6b7280",
    marginBottom: "4px",
    textTransform: "uppercase",
    fontWeight: 500,
  },
  formInput: {
    width: "100%",
    boxSizing: "border-box",
    fontSize: "0.95rem",
    color: "#2d3748",
    fontWeight: 500,
    margin: 0,
    background: "#fff",
    padding: "10px 12px",
    borderRadius: "8px",
    border: "1px solid #e5e7eb",
  },
  errorText: { color: "#ef4444", fontSize: "0.8rem", marginTop: "4px" },
  formFooter: {
    display: "flex",
    justifyContent: "flex-end",
    paddingTop: "24px",
    marginTop: "24px",
    borderTop: "1px solid #e2e8f0",
  },
  saveButton: {
    backgroundColor: "#10b981",
    color: "#fff",
    border: "none",
    borderRadius: "12px",
    padding: "12px 24px",
    fontWeight: 600,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  disabledButton: { backgroundColor: "#d1d5db", cursor: "not-allowed" },
};
export default styles;
