const styles = {
  contractsPageContainer: { fontFamily: "'Poppins', sans-serif" },
  contractsPageHeader: { marginBottom: "24px" },
  contractsPageHeaderH1: {
    fontSize: "2.25rem",
    fontWeight: 700,
    color: "#1a202c",
  },
  tableControlsHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "24px",
    gap: "16px",
  },
  searchBox: {
    flexGrow: 1,
    display: "flex",
    alignItems: "center",
    background: "#fff",
    borderRadius: "12px",
    padding: "0 16px",
    border: "1px solid #e5e7eb",
    boxShadow: "0px 4px 20px rgba(0, 0, 0, 0.04)",
  },
  searchBoxIcon: { color: "#9ca3af" },
  searchInput: {
    flexGrow: 1,
    border: "none",
    outline: "none",
    padding: "12px 8px",
    background: "transparent",
    fontFamily: "'Poppins', sans-serif",
    fontSize: "0.9rem",
  },

  // Estilos para o novo filtro
  filters: { display: "flex", gap: "12px" },
  filterSelect: {
    background: "#fff",
    border: "1px solid #e5e7eb",
    borderRadius: "12px",
    padding: "12px 16px",
    fontFamily: "'Poppins', sans-serif",
    fontSize: "0.9rem",
    cursor: "pointer",
    boxShadow: "0px 4px 20px rgba(0, 0, 0, 0.04)",
    minWidth: "180px",
  },

  contractsTableCard: {
    background: "rgba(255, 255, 255, 0.6)",
    backdropFilter: "blur(10px)",
    WebkitBackdropFilter: "blur(10px)",
    borderRadius: "16px",
    border: "1px solid rgba(255, 255, 255, 0.25)",
    boxShadow: "0px 4px 20px rgba(0, 0, 0, 0.04)",
    padding: "16px",
    overflowX: "auto",
  },
  contractsTable: { width: "100%", borderCollapse: "collapse" },
  tableHeader: {
    fontSize: "0.75rem",
    color: "#6b7280",
    textTransform: "uppercase",
    fontWeight: 600,
    letterSpacing: "0.05em",
  },
  tableCell: {
    padding: "16px 20px",
    textAlign: "left",
    borderBottom: "1px solid #f3f4f6",
    fontSize: "0.9rem",
    color: "#2d3748",
    fontWeight: 500,
  },
  tableRow: { cursor: "pointer", transition: "background-color 0.2s" },
  tableRowHover: { backgroundColor: "rgba(255, 255, 255, 0.7)" },
  statusBadge: {
    padding: "4px 10px",
    borderRadius: "12px",
    fontSize: "0.75rem",
    fontWeight: 600,
    textTransform: "uppercase",
  },
  statusValorizando: { backgroundColor: "#def7ec", color: "#03543f" },
  statusPendente: { backgroundColor: "#fef3c7", color: "#92400e" },
  statusFinalizado: { backgroundColor: "#e5e7eb", color: "#4b5563" },
  statusCancelado: { backgroundColor: "#fee2e2", color: "#991b1b" },
  paginationContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "24px 0 8px 0",
    gap: "16px",
  },
  paginationButton: {
    backgroundColor: "#fff",
    border: "1px solid #e5e7eb",
    color: "#374151",
    padding: "8px 16px",
    borderRadius: "8px",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  paginationButtonHover: { backgroundColor: "#f3f4f6", borderColor: "#d1d5db" },
  paginationButtonDisabled: { opacity: 0.5, cursor: "not-allowed" },
  tableRowSelected: { backgroundColor: "rgba(59, 130, 246, 0.1)" },
  bulkActionsBar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "12px 20px",
    backgroundColor: "#1f2937",
    color: "#fff",
    borderRadius: "12px",
    marginBottom: "24px",
    animation: "fadeIn 0.3s ease",
  },
  bulkActionButton: {
    border: "none",
    borderRadius: "8px",
    padding: "8px 16px",
    marginLeft: "12px",
    fontWeight: 500,
    color: "#fff",
    cursor: "pointer",
  },
  actionButtons: { display: "flex", gap: "8px" },
  actionButton: {
    border: "none",
    width: "32px",
    height: "32px",
    borderRadius: "8px",
    cursor: "pointer",
    fontSize: "0.9rem",
    color: "#fff",
    transition: "all 0.2s",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  approveBtn: { backgroundColor: "#10b981" },
  denyBtn: { backgroundColor: "#ef4444" },
};

export default styles;
